import Foundation

/// The serialized kind of a template field.
public enum FieldKind: String, Codable, Sendable, Hashable {
    case string
    case richText
    case number
    case bool
    case color
    case date
    case image
    case enumeration
    case array
    case record
    case file
}

public enum FieldEditor: Sendable, Hashable {
    case automatic
    case singleLine
    case multiLine
    case date
    case enumeration
    case color
    case currency(codeField: String?)
    case stringList
}

extension FieldEditor: Codable {
    private enum CodingKeys: String, CodingKey {
        case type
        case codeField
    }

    private enum EditorType: String, Codable {
        case automatic
        case singleLine
        case multiLine
        case date
        case enumeration
        case color
        case currency
        case stringList
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(EditorType.self, forKey: .type)
        switch type {
        case .automatic:
            self = .automatic
        case .singleLine:
            self = .singleLine
        case .multiLine:
            self = .multiLine
        case .date:
            self = .date
        case .enumeration:
            self = .enumeration
        case .color:
            self = .color
        case .currency:
            self = .currency(codeField: try container.decodeIfPresent(String.self, forKey: .codeField))
        case .stringList:
            self = .stringList
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .automatic:
            try container.encode(EditorType.automatic, forKey: .type)
        case .singleLine:
            try container.encode(EditorType.singleLine, forKey: .type)
        case .multiLine:
            try container.encode(EditorType.multiLine, forKey: .type)
        case .date:
            try container.encode(EditorType.date, forKey: .type)
        case .enumeration:
            try container.encode(EditorType.enumeration, forKey: .type)
        case .color:
            try container.encode(EditorType.color, forKey: .type)
        case .currency(let codeField):
            try container.encode(EditorType.currency, forKey: .type)
            try container.encodeIfPresent(codeField, forKey: .codeField)
        case .stringList:
            try container.encode(EditorType.stringList, forKey: .type)
        }
    }
}

public struct EnumOption: Codable, Sendable, Hashable, Identifiable {
    public let value: String
    public let label: String
    public let icon: String?

    public var id: String { value }

    public init(value: String, label: String, icon: String? = nil) {
        self.value = value
        self.label = label
        self.icon = icon
    }
}

/// Describes a sidecar file field: the file lives alongside `slop.json` in the package directory.
public struct FileFieldDescriptor: Codable, Sendable, Hashable {
    /// File extension without dot, e.g. "md", "csv", "txt"
    public let fileExtension: String
    /// MIME type, e.g. "text/markdown"
    public let mimeType: String?
    /// true = String bindings, false = Data bindings
    public let isText: Bool
    /// Default filename inside the package, e.g. "content.md"
    public let defaultFilename: String

    public init(
        fileExtension: String,
        mimeType: String? = nil,
        isText: Bool = true,
        defaultFilename: String
    ) {
        self.fileExtension = fileExtension
        self.mimeType = mimeType
        self.isText = isText
        self.defaultFilename = defaultFilename
    }
}

/// Describes a single field in a template's data model.
/// Generated by the @Template macro and serialized into the installed template manifest.
public struct FieldDescriptor: Codable, Sendable, Hashable {
    /// Property key matching the Swift struct property name
    public let key: String

    /// Human-readable label shown in the inspector
    public let label: String

    /// The field's serialized kind
    public let kind: FieldKind

    /// Whether the field must have a value present.
    public let required: Bool

    /// Default value for this field
    public let defaultValue: FieldValue

    /// Placeholder/help text shown in host-generated editors.
    public let hint: String?

    /// Validation constraints (e.g. min/max for numbers)
    public let constraints: [Constraint]

    /// For enum fields: the allowed options
    public let options: [EnumOption]?

    /// For array fields: the primitive kind of each element when the array is
    /// not record-backed.
    public let arrayItemKind: FieldKind?

    /// For array fields: schema of each array item.
    public let itemSchema: Schema?

    /// For record fields: nested schema.
    public let recordSchema: Schema?

    /// For file fields: sidecar file descriptor.
    public let fileDescriptor: FileFieldDescriptor?

    /// Preferred editor presentation in generated host UIs.
    public let editor: FieldEditor

    public init(
        key: String,
        label: String,
        kind: FieldKind,
        required: Bool = true,
        defaultValue: FieldValue = .null,
        hint: String? = nil,
        constraints: [Constraint] = [],
        options: [EnumOption]? = nil,
        arrayItemKind: FieldKind? = nil,
        itemSchema: Schema? = nil,
        recordSchema: Schema? = nil,
        fileDescriptor: FileFieldDescriptor? = nil,
        editor: FieldEditor = .automatic
    ) {
        self.key = key
        self.label = label
        self.kind = kind
        self.required = required
        self.defaultValue = defaultValue
        self.hint = hint
        self.constraints = constraints
        self.options = options
        self.arrayItemKind = arrayItemKind
        self.itemSchema = itemSchema
        self.recordSchema = recordSchema
        self.fileDescriptor = fileDescriptor
        self.editor = editor
    }
}

public extension FieldDescriptor {
    var resolvedEditor: FieldEditor {
        if editor != .automatic {
            return editor
        }

        switch kind {
        case .richText:
            return .multiLine
        case .date:
            return .date
        case .enumeration:
            return .enumeration
        case .color:
            return .color
        case .array where arrayItemKind == .string:
            return .stringList
        default:
            return .singleLine
        }
    }

    var hasPrimitiveArrayItems: Bool {
        kind == .array && arrayItemKind != nil
    }
}
