import Foundation

/// A section grouping related fields in the inspector UI.
public struct SchemaSection: Codable, Sendable, Hashable {
    public let title: String
    public let fields: [FieldDescriptor]

    public init(_ title: String, fields: [FieldDescriptor]) {
        self.title = title
        self.fields = fields
    }
}

/// Complete schema for a template's data model.
/// Generated by @Template macro and serialized into the installed template manifest.
/// The host reads this to build the inspector UI without loading the bundle executable.
public struct Schema: Codable, Sendable, Hashable {
    public let sections: [SchemaSection]

    public init(sections: [SchemaSection]) {
        self.sections = sections
    }

    /// All field descriptors across all sections, flattened.
    public var allFields: [FieldDescriptor] {
        sections.flatMap(\.fields)
    }

    /// Look up a field descriptor by key.
    public func field(forKey key: String) -> FieldDescriptor? {
        allFields.first { $0.key == key }
    }

    /// Generate default data values from schema.
    public func defaultValues() -> [String: FieldValue] {
        var result: [String: FieldValue] = [:]
        for field in allFields {
            result[field.key] = field.defaultValue
        }
        return result
    }
}
