import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct BudgetItem: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Name") var name: String = ""
    @Field("Amount") var amount: Double = 0
}

@SlopData
public struct BudgetCategory: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Name") var name: String = ""
    @Field("Icon") var icon: String = "💰"
    @Field("Color") var color: String = "#4a90d9"
    @Field("Items") var items: [BudgetItem] = []

    var total: Double { items.reduce(0) { $0 + $1.amount } }
}

@SlopData
public struct BudgetData {
    @Field("Title") var title: String = "Monthly Budget"
    @Field("Currency", options: ["USD", "EUR", "GBP", "JPY"]) var currency: String = "USD"
    @Field("Income") var income: Double = 5000
    @Field("Categories") var categories: [BudgetCategory] = BudgetData.defaultCategories

    var totalExpenses: Double { categories.reduce(0) { $0 + $1.total } }
    var remaining: Double { income - totalExpenses }

    var daysInMonth: Int {
        let cal = Calendar.current
        let range = cal.range(of: .day, in: .month, for: Date())
        return range?.count ?? 30
    }

    var dayOfMonth: Int {
        Calendar.current.component(.day, from: Date())
    }

    var remainingPerDay: Double {
        let daysLeft = max(daysInMonth - dayOfMonth, 1)
        return remaining / Double(daysLeft)
    }
}

extension BudgetData {
    static var defaultCategories: [BudgetCategory] {
        func item(_ name: String, _ amount: Double) -> BudgetItem {
            var i = BudgetItem()
            i.name = name
            i.amount = amount
            return i
        }

        func category(_ name: String, _ color: String, _ items: [BudgetItem]) -> BudgetCategory {
            var c = BudgetCategory()
            c.name = name
            c.color = color
            c.items = items
            return c
        }

        return [
            category("Housing", "#e8608a", [item("Rent", 1500), item("Utilities", 150)]),
            category("Food", "#f5a623", [item("Groceries", 400), item("Dining Out", 150)]),
            category("Transport", "#4a90d9", [item("Gas", 100), item("Insurance", 120)]),
            category("Savings", "#50c878", [item("Emergency Fund", 500)]),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.budget-tracker",
    name: "Budget Tracker",
    description: "Track income, category budgets, and spending totals at a glance.",
    version: "2.0.0",
    width: 360, height: 600,
    minWidth: 320, minHeight: 400,
    shape: .roundedRect(radius: 16),
    theme: "rose",
    alwaysOnTop: true,
    categories: ["popular", "finance"]
)
struct BudgetView: View {
    @TemplateData var data: BudgetData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Budget Title", text: $data.title)
                    .font(theme.title(size: 22))
                    .foregroundStyle(theme.foreground)

                // Donut chart centered
                HStack {
                    Spacer()
                    DonutChart(
                        segments: data.categories.map { cat in
                            DonutSegment(
                                color: colorFromHex(cat.color),
                                fraction: data.totalExpenses > 0 ? cat.total / data.totalExpenses : 0,
                                label: cat.name
                            )
                        },
                        centerLabel: formatted(data.remaining),
                        size: 100,
                        lineWidth: 16,
                        backgroundColor: theme.surface
                    )
                    Spacer()
                }

                // Remaining per day
                HStack {
                    Spacer()
                    VStack(spacing: 2) {
                        Text(formatted(data.remainingPerDay))
                            .font(theme.font(size: 14, weight: .semibold))
                            .foregroundStyle(data.remainingPerDay >= 0 ? theme.accent : .red)
                            .contentTransition(.numericText())
                        Text("per day remaining")
                            .font(theme.font(size: 10))
                            .foregroundStyle(theme.secondary.opacity(0.6))
                    }
                    Spacer()
                }

                ThemeDivider()

                ColumnBarChart(
                    items: data.categories.map { cat in
                        BarChartItem(
                            name: cat.name,
                            value: cat.total,
                            color: colorFromHex(cat.color),
                            formattedValue: formatted(cat.total)
                        )
                    }
                )

                ThemeDivider()

                HStack {
                    Text("Income")
                        .foregroundStyle(theme.secondary)
                    Spacer()
                    CurrencyInput(
                        currency: data.currency,
                        value: $data.income,
                        symbolColor: theme.accent,
                        valueColor: theme.accent
                    )
                }

                ForEach($data.categories) { $category in
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            SlopEmojiPicker($category.icon)
                                .font(.system(size: 16))

                            RoundedRectangle(cornerRadius: 2)
                                .fill(colorFromHex(category.color))
                                .frame(width: 4, height: 16)
                            SlopTextField("Category", text: $category.name)
                                .font(.caption.weight(.medium))
                                .foregroundStyle(theme.secondary)
                            Spacer()
                            Text(formatted(category.total))
                                .font(.caption)
                                .foregroundStyle(theme.secondary.opacity(0.6))
                            RemoveButton {
                                withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                    data.categories.removeAll { $0.id == category.id }
                                }
                            }
                        }

                        SlopInteractiveOnly {
                            SlopColorField(hex: $category.color)
                        }

                        ForEach($category.items) { $item in
                            HStack(spacing: 8) {
                                SlopTextField("Item name", text: $item.name)
                                    .foregroundStyle(theme.foreground.opacity(0.8))
                                Spacer()
                                HStack(spacing: 2) {
                                    Text(currencySymbol(for: data.currency))
                                        .foregroundStyle(theme.secondary)
                                        .font(theme.font(size: 12))
                                    SlopNumberField("0", value: $item.amount)
                                        .foregroundStyle(theme.foreground.opacity(0.8))
                                        .multilineTextAlignment(.trailing)
                                        .frame(width: 70)
                                }
                                RemoveButton {
                                    withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                        $category.wrappedValue.items.removeAll {
                                            $0.id == item.id
                                        }
                                    }
                                }
                            }
                        }

                        AddItemButton("Add Item") {
                            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                $category.wrappedValue.items.append(BudgetItem())
                            }
                        }
                    }
                }

                AddItemButton("Add Category") {
                    withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                        var cat = BudgetCategory()
                        cat.name = "New Category"
                        data.categories.append(cat)
                    }
                }

                ThemeDivider()

                SummaryRow(
                    label: "Total Expenses",
                    value: formatted(data.totalExpenses),
                    valueColor: .red.opacity(0.8)
                )

                SummaryRow(
                    label: "Remaining",
                    value: formatted(data.remaining),
                    valueColor: data.remaining >= 0 ? theme.accent : .red,
                    isBold: true
                )
                .font(.title3)

                // Overall progress bar
                let spent = min(data.totalExpenses / max(data.income, 1), 1.0)
                ProgressBar(
                    progress: spent,
                    fillColor: spent > 0.9 ? Color.red : theme.accent,
                    backgroundColor: theme.surface,
                    height: 8
                )
            }
            .padding(24)
        }
        .background(theme.background)
    }

    // MARK: - Helpers

    private func formatted(_ value: Double) -> String {
        formatCurrency(value, code: data.currency)
    }
}
