import Foundation
import SwiftUI
import SlopKit
import AppKit

// MARK: - Data Model

@SlopData
public struct PaletteColor: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Hex") var hex: String = "#FF6B6B"
    @Field("Name") var name: String = ""
    @Field("Locked") var locked: Bool = false
}

@SlopData
public struct ColorPaletteData {
    @Field("Title") var title: String = "Color Palette"
    @Field("Palette Name") var paletteName: String = "Sunset Vibes"
    @Field("Colors") var colors: [PaletteColor] = ColorPaletteData.defaultColors
}

extension ColorPaletteData {
    static var defaultColors: [PaletteColor] {
        func color(_ hex: String, _ name: String) -> PaletteColor {
            var c = PaletteColor()
            c.hex = hex
            c.name = name
            return c
        }
        return [
            color("#FF6B6B", "Coral"),
            color("#4ECDC4", "Teal"),
            color("#45B7D1", "Sky"),
            color("#96CEB4", "Sage"),
            color("#FFEAA7", "Butter"),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.color-palette",
    name: "Color Palette",
    description: "Collect and present a curated set of brand or project colors with their hex values.",
    version: "1.0.0",
    width: 320, height: 580,
    minWidth: 280, minHeight: 400,
    shape: .roundedRect(radius: 16),
    alwaysOnTop: true,
    categories: ["design"]
)
struct ColorPaletteView: View {
    @TemplateData var data: ColorPaletteData
    @Environment(\.slopTheme) private var theme

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header

            Divider().background(theme.divider)

            SlopContent {
                VStack(spacing: 10) {
                    ForEach($data.colors) { $color in
                        SwatchRow(color: $color) {
                            withAnimation { data.colors.removeAll { $0.id == color.id } }
                        }
                    }
                }
                .padding(.horizontal, 16)
                .padding(.vertical, 12)
            }

            Divider().background(theme.divider)

            SlopInteractiveOnly {
                footer
            }
        }
        .background(theme.background)
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                SlopTextField("Title", text: $data.title)
                    .font(theme.font(size: 18, weight: .bold))
                    .foregroundStyle(theme.foreground)

                Spacer()

                Text("\(data.colors.count) colors")
                    .font(.caption)
                    .foregroundStyle(theme.secondary)
            }

            SlopTextField("Palette name", text: $data.paletteName)
                .font(theme.font(size: 12))
                .foregroundStyle(theme.secondary)
        }
        .padding(.horizontal, 16)
        .padding(.top, 12)
        .padding(.bottom, 8)
    }

    private var footer: some View {
        HStack(spacing: 12) {
            Button {
                withAnimation {
                    randomizeUnlocked()
                }
            } label: {
                Label("Randomize", systemImage: "dice")
                    .font(theme.font(size: 12, weight: .medium))
                    .foregroundStyle(theme.accent)
            }
            .buttonStyle(.plain)

            Spacer()

            Button {
                withAnimation {
                    var c = PaletteColor()
                    c.hex = randomPleasantHex()
                    c.name = "New"
                    data.colors.append(c)
                }
            } label: {
                Label("Add", systemImage: "plus")
                    .font(theme.font(size: 12, weight: .medium))
                    .foregroundStyle(theme.secondary)
            }
            .buttonStyle(.plain)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
    }

    // MARK: Helpers

    private func randomizeUnlocked() {
        for i in data.colors.indices {
            if !data.colors[i].locked {
                data.colors[i].hex = randomPleasantHex()
            }
        }
    }
}

// MARK: - Swatch Row

private struct SwatchRow: View {
    @Binding var color: PaletteColor
    let onDelete: () -> Void
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget
    @State private var copiedID: String?

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            // Large swatch
            RoundedRectangle(cornerRadius: 8)
                .fill(colorFromHex(color.hex))
                .frame(height: 36)
                .overlay(
                    Group {
                        if copiedID == color.id {
                            Text("Copied!")
                                .font(theme.font(size: 11, weight: .semibold))
                                .foregroundStyle(.white)
                                .padding(.horizontal, 8)
                                .padding(.vertical, 4)
                                .background(
                                    Capsule().fill(.black.opacity(0.5))
                                )
                                .transition(.opacity)
                        }
                    }
                )
                .onTapGesture {
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(color.hex.uppercased(), forType: .string)
                    withAnimation(.easeInOut(duration: 0.15)) { copiedID = color.id }
                    DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                        withAnimation(.easeInOut(duration: 0.2)) { copiedID = nil }
                    }
                }

            // Info row
            HStack(spacing: 6) {
                if renderTarget == .interactive {
                    TextField("Name", text: $color.name)
                        .font(theme.font(size: 12, weight: .medium))
                        .foregroundStyle(theme.foreground)
                        .textFieldStyle(.plain)
                        .frame(maxWidth: .infinity, alignment: .leading)

                    TextField("#000000", text: $color.hex)
                        .font(theme.mono(size: 11))
                        .foregroundStyle(theme.secondary)
                        .textFieldStyle(.plain)
                        .frame(width: 72)
                        .multilineTextAlignment(.trailing)

                    SlopColorField(hex: $color.hex)

                    Button {
                        withAnimation { color.locked.toggle() }
                    } label: {
                        Image(systemName: color.locked ? "lock.fill" : "lock.open")
                            .font(theme.font(size: 10, weight: .medium))
                            .foregroundStyle(color.locked ? theme.accent : theme.secondary.opacity(0.4))
                    }
                    .buttonStyle(.plain)

                    Button(action: onDelete) {
                        Image(systemName: "xmark")
                            .font(theme.font(size: 9, weight: .bold))
                            .foregroundStyle(theme.secondary.opacity(0.4))
                    }
                    .buttonStyle(.plain)
                } else {
                    Text(color.name)
                        .font(theme.font(size: 12, weight: .medium))
                        .foregroundStyle(theme.foreground)
                        .frame(maxWidth: .infinity, alignment: .leading)

                    Text(color.hex.uppercased())
                        .font(theme.mono(size: 11))
                        .foregroundStyle(theme.secondary)
                }
            }
        }
        .padding(8)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(theme.surface.opacity(0.4))
        )
    }
}

// MARK: - Color Helpers

private func randomPleasantHex() -> String {
    // Generate pastel / pleasant colors by keeping saturation moderate
    // HSB approach: hue random, saturation 40-70%, brightness 70-95%
    let hue = Double.random(in: 0...1)
    let saturation = Double.random(in: 0.4...0.7)
    let brightness = Double.random(in: 0.7...0.95)

    // Convert HSB to RGB
    let c = brightness * saturation
    let x = c * (1 - abs((hue * 6).truncatingRemainder(dividingBy: 2) - 1))
    let m = brightness - c

    let rp, gp, bp: Double
    switch Int(hue * 6) {
    case 0: (rp, gp, bp) = (c, x, 0)
    case 1: (rp, gp, bp) = (x, c, 0)
    case 2: (rp, gp, bp) = (0, c, x)
    case 3: (rp, gp, bp) = (0, x, c)
    case 4: (rp, gp, bp) = (x, 0, c)
    default: (rp, gp, bp) = (c, 0, x)
    }

    let r = Int((rp + m) * 255)
    let g = Int((gp + m) * 255)
    let b = Int((bp + m) * 255)

    return String(format: "#%02X%02X%02X", r, g, b)
}

