import Foundation
import SwiftUI
import SlopKit

// MARK: - Data Model

@SlopData
public struct CountdownEvent: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Name") var name: String = ""
    @Field("Target Date") var targetDate: Date = Date().addingTimeInterval(30 * 24 * 3600)
    @Field("Color") var color: String = "#e8608a"
}

@SlopData
public struct CountdownData {
    @SlopKit.Section("Overview")
    @Field("Title") var title: String = "Countdowns"
    @Field("Subtitle") var subtitle: String = "Upcoming Events"

    @SlopKit.Section("Events")
    @Field("Events") var events: [CountdownEvent] = CountdownData.defaultEvents
}

extension CountdownData {
    static var defaultEvents: [CountdownEvent] {
        func event(_ name: String, daysOut: Int, color: String) -> CountdownEvent {
            var e = CountdownEvent()
            e.name = name
            e.targetDate = Date().addingTimeInterval(Double(daysOut) * 24 * 3600)
            e.color = color
            return e
        }

        return [
            event("Product Launch", daysOut: 14, color: "#e8608a"),
            event("Team Offsite", daysOut: 30, color: "#00bcd4"),
            event("Birthday", daysOut: 60, color: "#b388ff"),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.countdown",
    name: "Countdown",
    description: "Pin a live countdown to an important deadline, launch, or event.",
    version: "1.0.0",
    width: 360, height: 480,
    shape: .roundedRect(radius: 20),
    theme: "rose",
    alwaysOnTop: true,
    categories: ["events"]
)
struct CountdownView: View {
    @TemplateData var data: CountdownData
    @Environment(\.slopTheme) private var theme

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Title", text: $data.title)
                    .font(theme.title(size: 22))
                    .foregroundStyle(theme.foreground)

                SlopTextField("Subtitle", text: $data.subtitle)
                    .font(.subheadline)
                    .foregroundStyle(theme.secondary)

                Divider().background(theme.divider)

                ForEach(sortedEventIds, id: \.self) { eventId in
                    eventRow(eventId: eventId)
                }

                SlopInteractiveOnly {
                    Button {
                        withAnimation {
                            var e = CountdownEvent()
                            e.name = "New Event"
                            data.events.append(e)
                        }
                    } label: {
                        Label("Add Event", systemImage: "plus")
                            .font(.caption)
                            .foregroundStyle(theme.secondary.opacity(0.6))
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(24)
        }
        .background(theme.background)
    }

    // MARK: Helpers

    private var sortedEventIds: [String] {
        data.events.sorted(by: { $0.targetDate < $1.targetDate }).map(\.id)
    }

    private func eventBinding(for eventId: String) -> Binding<CountdownEvent> {
        Binding(
            get: { data.events.first(where: { $0.id == eventId }) ?? CountdownEvent() },
            set: { newValue in
                if let idx = data.events.firstIndex(where: { $0.id == eventId }) {
                    data.events[idx] = newValue
                }
            }
        )
    }

    @ViewBuilder
    private func eventRow(eventId: String) -> some View {
        let binding = eventBinding(for: eventId)
        let event = binding.wrappedValue
        HStack(spacing: 0) {
            RoundedRectangle(cornerRadius: 3)
                .fill(colorFromHex(event.color))
                .frame(width: 6)

            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    SlopTextField("Event name", text: binding.name)
                        .font(.headline)
                        .foregroundStyle(theme.foreground)
                    Spacer()
                    SlopInteractiveOnly {
                        Button {
                            withAnimation {
                                data.events.removeAll { $0.id == eventId }
                            }
                        } label: {
                            Image(systemName: "minus.circle.fill")
                                .font(.caption)
                                .foregroundStyle(theme.secondary.opacity(0.4))
                        }
                        .buttonStyle(.plain)
                    }
                }

                SlopEditable(binding.targetDate) { value in
                    Text(value, style: .date)
                        .font(.caption)
                        .foregroundStyle(theme.secondary)
                } editor: { $value in
                    DatePicker("Date", selection: $value, displayedComponents: .date)
                        .font(.caption)
                        .foregroundStyle(theme.secondary)
                        .labelsHidden()
                }

                HStack(alignment: .firstTextBaseline, spacing: 4) {
                    Text("\(daysRemaining(until: event.targetDate))")
                        .font(theme.title(size: 32))
                        .foregroundStyle(colorFromHex(event.color))
                    Text("days")
                        .font(.caption)
                        .foregroundStyle(theme.secondary)
                }

                SlopInteractiveOnly {
                    SlopColorField(hex: binding.color)
                }
            }
            .padding(12)
        }
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(theme.surface)
        )
    }

    private func daysRemaining(until date: Date) -> Int {
        Calendar.current.dateComponents([.day], from: Date(), to: date).day ?? 0
    }
}

