import Foundation
import SwiftUI
import SlopKit

// MARK: - Data Model

@SlopData
public struct Quote: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Text") var text: String = ""
    @Field("Author") var author: String = ""
}

@SlopData
public struct DailyQuoteData {
    @SlopKit.Section("Settings")
    @Field("Title") var title: String = "Daily Quote"
    @Field("Current Index") var currentIndex: Double = 0
    @Field("Last Shown Date") var lastShownDate: String = ""

    @SlopKit.Section("Quotes")
    @Field("Quotes") var quotes: [Quote] = DailyQuoteData.defaultQuotes

    var safeIndex: Int {
        guard !quotes.isEmpty else { return 0 }
        return Int(currentIndex) % quotes.count
    }

    var currentQuote: Quote? {
        guard !quotes.isEmpty else { return nil }
        return quotes[safeIndex]
    }
}

extension DailyQuoteData {
    static var defaultQuotes: [Quote] {
        func quote(_ text: String, _ author: String) -> Quote {
            var q = Quote()
            q.text = text
            q.author = author
            return q
        }

        return [
            quote("We suffer more often in imagination than in reality.", "Seneca"),
            quote("The obstacle is the way.", "Marcus Aurelius"),
            quote("A journey of a thousand miles begins with a single step.", "Lao Tzu"),
            quote("Imagination is more important than knowledge.", "Albert Einstein"),
            quote("The first principle is that you must not fool yourself -- and you are the easiest person to fool.", "Richard Feynman"),
            quote("Somewhere, something incredible is waiting to be known.", "Carl Sagan"),
            quote("Not all those who wander are lost.", "J.R.R. Tolkien"),
            quote("There is no greater agony than bearing an untold story inside you.", "Maya Angelou"),
            quote("The only way to do great work is to love what you do.", "Steve Jobs"),
            quote("In the middle of difficulty lies opportunity.", "Albert Einstein"),
            quote("He who has a why to live can bear almost any how.", "Friedrich Nietzsche"),
            quote("The unexamined life is not worth living.", "Socrates"),
            quote("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"),
            quote("It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.", "Charles Darwin"),
            quote("If you want to go fast, go alone. If you want to go far, go together.", "African Proverb"),
            quote("The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", "Ralph Waldo Emerson"),
            quote("One must imagine Sisyphus happy.", "Albert Camus"),
            quote("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
            quote("The cosmos is within us. We are made of star-stuff.", "Carl Sagan"),
            quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.daily-quote",
    name: "Daily Quote",
    description: "Display a favorite quote and attribution in a compact inspirational card.",
    version: "1.0.0",
    width: 360, height: 280,
    shape: .roundedRect(radius: 24),
    alwaysOnTop: true,
    categories: ["personal"]
)
struct DailyQuoteView: View {
    @TemplateData var data: DailyQuoteData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    @State private var displayedIndex: Int = 0

    private var todayString: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: Date())
    }

    var body: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                SlopTextField("Title", text: $data.title)
                    .font(theme.font(size: 13, weight: .semibold))
                    .foregroundStyle(theme.secondary)

                Spacer()

                SlopInteractiveOnly {
                    Text("\(data.safeIndex + 1)/\(data.quotes.count)")
                        .font(theme.mono(size: 11, weight: .medium))
                        .foregroundStyle(theme.secondary.opacity(0.6))
                }
            }
            .padding(.horizontal, 24)
            .padding(.top, 20)
            .padding(.bottom, 8)

            Divider()
                .background(theme.divider)
                .padding(.horizontal, 24)

            // Quote body
            Spacer()

            if !data.quotes.isEmpty {
                VStack(spacing: 12) {
                    SlopEditable(quoteTextBinding) { value in
                        Text(value)
                            .font(theme.font(size: 18, weight: .medium))
                            .foregroundStyle(theme.foreground)
                            .multilineTextAlignment(.center)
                            .lineSpacing(4)
                    } editor: { binding in
                        TextField("Quote text", text: binding)
                            .font(theme.font(size: 18, weight: .medium))
                            .foregroundStyle(theme.foreground)
                            .multilineTextAlignment(.center)
                            .textFieldStyle(.plain)
                    }
                    .id(displayedIndex)
                    .transition(.asymmetric(
                        insertion: .move(edge: .trailing).combined(with: .opacity),
                        removal: .move(edge: .leading).combined(with: .opacity)
                    ))

                    SlopEditable(quoteAuthorBinding) { value in
                        Text("\u{2014} \(value)")
                            .font(theme.font(size: 13))
                            .foregroundStyle(theme.secondary)
                    } editor: { binding in
                        TextField("Author", text: binding)
                            .font(theme.font(size: 13))
                            .foregroundStyle(theme.secondary)
                            .multilineTextAlignment(.center)
                            .textFieldStyle(.plain)
                    }
                    .id("author-\(displayedIndex)")
                    .transition(.asymmetric(
                        insertion: .move(edge: .trailing).combined(with: .opacity),
                        removal: .move(edge: .leading).combined(with: .opacity)
                    ))
                }
                .padding(.horizontal, 28)
            } else {
                Text("No quotes yet")
                    .font(theme.font(size: 14))
                    .foregroundStyle(theme.secondary)
            }

            Spacer()

            // Navigation (interactive only)
            SlopInteractiveOnly {
                HStack {
                    Button { navigatePrev() } label: {
                        Image(systemName: "chevron.left")
                            .font(theme.font(size: 14, weight: .medium))
                            .foregroundStyle(theme.secondary)
                            .frame(width: 32, height: 32)
                            .contentShape(Rectangle())
                    }
                    .buttonStyle(.plain)
                    .disabled(data.quotes.isEmpty)

                    Spacer()

                    Button {
                        withAnimation(.easeInOut(duration: 0.3)) {
                            var newQuote = Quote()
                            newQuote.text = "New quote"
                            newQuote.author = "Author"
                            data.quotes.append(newQuote)
                            data.currentIndex = Double(data.quotes.count - 1)
                            displayedIndex = data.safeIndex
                        }
                    } label: {
                        Image(systemName: "plus")
                            .font(theme.font(size: 12, weight: .medium))
                            .foregroundStyle(theme.secondary.opacity(0.6))
                    }
                    .buttonStyle(.plain)

                    Spacer()

                    Button { navigateNext() } label: {
                        Image(systemName: "chevron.right")
                            .font(theme.font(size: 14, weight: .medium))
                            .foregroundStyle(theme.secondary)
                            .frame(width: 32, height: 32)
                            .contentShape(Rectangle())
                    }
                    .buttonStyle(.plain)
                    .disabled(data.quotes.isEmpty)
                }
                .padding(.horizontal, 24)
                .padding(.bottom, 16)
            }
        }
        .background(theme.background)
        .onAppear { checkDailyRotation() }
    }

    // MARK: - Quote Bindings

    private var quoteTextBinding: Binding<String> {
        Binding<String>(
            get: { data.quotes.indices.contains(data.safeIndex) ? data.quotes[data.safeIndex].text : "" },
            set: { newValue in
                if data.quotes.indices.contains(data.safeIndex) {
                    data.quotes[data.safeIndex].text = newValue
                }
            }
        )
    }

    private var quoteAuthorBinding: Binding<String> {
        Binding<String>(
            get: { data.quotes.indices.contains(data.safeIndex) ? data.quotes[data.safeIndex].author : "" },
            set: { newValue in
                if data.quotes.indices.contains(data.safeIndex) {
                    data.quotes[data.safeIndex].author = newValue
                }
            }
        )
    }

    // MARK: - Daily Rotation

    private func checkDailyRotation() {
        let today = todayString
        if data.lastShownDate != today, !data.quotes.isEmpty {
            let nextIndex = (Int(data.currentIndex) + 1) % data.quotes.count
            data.currentIndex = Double(nextIndex)
            data.lastShownDate = today
        }
        displayedIndex = data.safeIndex
    }

    // MARK: - Navigation

    private func navigatePrev() {
        guard !data.quotes.isEmpty else { return }
        withAnimation(.easeInOut(duration: 0.3)) {
            let prev = (Int(data.currentIndex) - 1 + data.quotes.count) % data.quotes.count
            data.currentIndex = Double(prev)
            displayedIndex = data.safeIndex
        }
    }

    private func navigateNext() {
        guard !data.quotes.isEmpty else { return }
        withAnimation(.easeInOut(duration: 0.3)) {
            let next = (Int(data.currentIndex) + 1) % data.quotes.count
            data.currentIndex = Double(next)
            displayedIndex = data.safeIndex
        }
    }
}

