import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct Expense: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Date") var date: Date = .now
    @Field("Description") var description: String = ""
    @Field("Amount") var amount: Double = 0
    @Field("Category", options: ["Food", "Transport", "Shopping", "Entertainment", "Other"]) var category: String = "Food"
    @Field("Icon") var icon: String = "🍔"
}

@SlopData
public struct ExpenseTrackerData {
    @Field("Title") var title: String = "Daily Expenses"
    @Field("Currency", options: ["USD", "EUR", "GBP", "JPY"]) var currency: String = "USD"
    @Field("Expenses") var expenses: [Expense] = ExpenseTrackerData.defaultExpenses

    var totalAmount: Double { expenses.reduce(0) { $0 + $1.amount } }

    var categoryBreakdown: [(category: String, total: Double)] {
        let categories = ["Food", "Transport", "Shopping", "Entertainment", "Other"]
        return categories.compactMap { cat in
            let total = expenses.filter { $0.category == cat }.reduce(0) { $0 + $1.amount }
            return total > 0 ? (category: cat, total: total) : nil
        }
    }
}

extension ExpenseTrackerData {
    static var defaultExpenses: [Expense] {
        func expense(_ year: Int, _ month: Int, _ day: Int, _ description: String, _ amount: Double, _ category: String) -> Expense {
            var e = Expense()
            e.date = makeDate(year, month, day)
            e.description = description
            e.amount = amount
            e.category = category
            return e
        }

        return [
            expense(2025, 1, 15, "Lunch", 12, "Food"),
            expense(2025, 1, 15, "Bus fare", 3, "Transport"),
            expense(2025, 1, 15, "Headphones", 45, "Shopping"),
        ]
    }

    private static func makeDate(_ y: Int, _ m: Int, _ d: Int) -> Date {
        Calendar.current.date(from: DateComponents(year: y, month: m, day: d)) ?? .now
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.expense-tracker",
    name: "Expense Tracker",
    description: "Log expenses by category and watch your running totals update automatically.",
    version: "1.0.0",
    width: 380, height: 620,
    minWidth: 320, minHeight: 400,
    shape: .roundedRect(radius: 16),
    theme: "midnight",
    alwaysOnTop: true,
    categories: ["finance"]
)
struct ExpenseTrackerView: View {
    @TemplateData var data: ExpenseTrackerData
    @Environment(\.slopTheme) private var theme

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Expense Title", text: $data.title)
                    .font(theme.title(size: 22))
                    .foregroundStyle(theme.foreground)

                Divider().background(theme.divider)

                HStack {
                    Text("Currency")
                        .foregroundStyle(theme.secondary)
                    Spacer()
                    SlopEditable($data.currency) { value in
                        Text(value)
                            .foregroundStyle(theme.foreground)
                    } editor: { $value in
                        Picker("", selection: $value) {
                            Text("USD").tag("USD")
                            Text("EUR").tag("EUR")
                            Text("GBP").tag("GBP")
                            Text("JPY").tag("JPY")
                        }
                        .labelsHidden()
                        .frame(width: 80)
                    }
                }

                ForEach($data.expenses) { $expense in
                    VStack(alignment: .leading, spacing: 6) {
                        HStack {
                            SlopEmojiPicker($expense.icon)
                                .font(.system(size: 18))

                            SlopEditable($expense.date) { value in
                                Text(value, style: .date)
                                    .font(.caption)
                                    .foregroundStyle(theme.secondary)
                            } editor: { $value in
                                DatePicker("", selection: $value, displayedComponents: .date)
                                    .labelsHidden()
                            }
                            .frame(width: 90)
                            Spacer()
                            SlopEditable($expense.category) { value in
                                Text(value)
                                    .font(.caption.weight(.medium))
                                    .foregroundStyle(theme.secondary)
                            } editor: { $value in
                                Picker("", selection: $value) {
                                    Text("Food").tag("Food")
                                    Text("Transport").tag("Transport")
                                    Text("Shopping").tag("Shopping")
                                    Text("Entertainment").tag("Entertainment")
                                    Text("Other").tag("Other")
                                }
                                .labelsHidden()
                                .frame(width: 120)
                            }
                            RemoveButton {
                                withAnimation {
                                    data.expenses.removeAll { $0.id == expense.id }
                                }
                            }
                        }

                        HStack(spacing: 8) {
                            SlopTextField("Description", text: $expense.description)
                                .foregroundStyle(theme.foreground.opacity(0.8))
                            Spacer()
                            CurrencyInput(
                                currency: data.currency,
                                value: $expense.amount,
                                width: 70,
                                symbolColor: theme.secondary,
                                valueColor: theme.foreground.opacity(0.8)
                            )
                            .font(theme.font(size: 12))
                        }
                    }
                    .padding(.vertical, 4)
                }

                AddItemButton("Add Expense") {
                    withAnimation {
                        data.expenses.append(Expense())
                    }
                }

                Divider().background(theme.divider)

                // Category breakdown
                if !data.categoryBreakdown.isEmpty {
                    VStack(alignment: .leading, spacing: 8) {
                        SectionHeader("By Category")

                        ColumnBarChart(
                            items: data.categoryBreakdown.map { entry in
                                BarChartItem(
                                    name: entry.category,
                                    value: entry.total,
                                    color: theme.accent,
                                    formattedValue: formatted(entry.total)
                                )
                            },
                            barHeight: 6
                        )
                    }

                    Divider().background(theme.divider)
                }

                SummaryRow(
                    label: "Total",
                    value: formatted(data.totalAmount),
                    valueColor: theme.accent,
                    isBold: true
                )
                .font(.title3)
            }
            .padding(24)
        }
        .background(theme.background)
    }

    // MARK: - Helpers

    private func formatted(_ value: Double) -> String {
        "\(currencySymbol(for: data.currency))\(String(format: "%.0f", value))"
    }
}

