import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct ExerciseSet: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Reps") var reps: Double = 10
    @Field("Weight") var weight: Double = 0
}

@SlopData
public struct Exercise: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Name") var name: String = ""
    @Field("Sets") var sets: [ExerciseSet] = []
    @Field("Notes") var notes: String = ""

    var totalVolume: Double { sets.reduce(0) { $0 + $1.reps * $1.weight } }
    var totalSets: Int { sets.count }
    var totalReps: Double { sets.reduce(0) { $0 + $1.reps } }
    var maxWeight: Double { sets.map(\.weight).max() ?? 0 }
}

@SlopData
public struct FitnessLogData {
    @SlopKit.Section("Overview")
    @Field("Title") var title: String = "Workout Log"
    @Field("Date") var date: Date = .now
    @Field("Workout Type", options: ["Strength", "Cardio", "Flexibility", "HIIT"]) var workoutType: String = "Strength"

    @SlopKit.Section("Exercises")
    @Field("Exercises") var exercises: [Exercise] = FitnessLogData.defaultExercises

    @SlopKit.Section("Notes")
    @Field("Session Notes") var sessionNotes: String = "Felt strong today. Increase weight next session."

    var totalVolume: Double { exercises.reduce(0) { $0 + $1.totalVolume } }
    var totalExercises: Int { exercises.count }
    var totalSetsCount: Int { exercises.reduce(0) { $0 + $1.totalSets } }
}

extension FitnessLogData {
    static var defaultExercises: [Exercise] {
        func set(_ reps: Double, _ weight: Double) -> ExerciseSet {
            var s = ExerciseSet()
            s.reps = reps
            s.weight = weight
            return s
        }

        func exercise(_ name: String, _ sets: [ExerciseSet]) -> Exercise {
            var e = Exercise()
            e.name = name
            e.sets = sets
            return e
        }

        return [
            exercise("Bench Press", [set(10, 135), set(8, 155), set(6, 175)]),
            exercise("Squats", [set(10, 185), set(8, 205), set(6, 225)]),
            exercise("Deadlift", [set(8, 225), set(6, 275)]),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.fitness-log",
    name: "Fitness Log",
    description: "Record workouts, sets, reps, and notes in a focused training journal.",
    version: "1.0.0",
    width: 400, height: 600,
    minWidth: 340, minHeight: 480,
    shape: .roundedRect(radius: 20),
    theme: "sunset",
    alwaysOnTop: true,
    categories: ["health"]
)
struct FitnessLogView: View {
    @TemplateData var data: FitnessLogData
    @Environment(\.slopTheme) private var theme

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Workout Title", text: $data.title)
                    .font(theme.title(size: 22))
                    .foregroundStyle(theme.foreground)

                HStack {
                    SlopEditable($data.date) { value in
                        Text(value, style: .date)
                            .foregroundStyle(theme.secondary)
                    } editor: { $value in
                        DatePicker("", selection: $value, displayedComponents: .date)
                            .labelsHidden()
                    }
                    Spacer()
                    SlopEditable($data.workoutType) { value in
                        Text(value)
                            .foregroundStyle(theme.accent)
                    } editor: { $value in
                        Picker("", selection: $value) {
                            Text("Strength").tag("Strength")
                            Text("Cardio").tag("Cardio")
                            Text("Flexibility").tag("Flexibility")
                            Text("HIIT").tag("HIIT")
                        }
                        .labelsHidden()
                        .foregroundStyle(theme.accent)
                    }
                }

                // Session summary
                sessionSummary

                Divider().background(theme.divider)

                // Volume chart
                if !data.exercises.isEmpty {
                    volumeBarChart
                    Divider().background(theme.divider)
                }

                ForEach($data.exercises) { $exercise in
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            SlopTextField("Exercise", text: $exercise.name)
                                .font(.headline)
                                .foregroundStyle(theme.foreground)
                            Spacer()
                            Text("Vol: \(formattedVolume(exercise.totalVolume))")
                                .font(.caption)
                                .foregroundStyle(theme.secondary.opacity(0.6))
                                .contentTransition(.numericText())
                            SlopInteractiveOnly {
                                Button {
                                    withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                        data.exercises.removeAll { $0.id == exercise.id }
                                    }
                                } label: {
                                    Image(systemName: "minus.circle.fill")
                                        .font(.caption)
                                        .foregroundStyle(theme.secondary.opacity(0.4))
                                }
                                .buttonStyle(.plain)
                            }
                        }

                        HStack(spacing: 0) {
                            Text("Set")
                                .frame(width: 32, alignment: .leading)
                            Text("Reps")
                                .frame(width: 60, alignment: .trailing)
                            Text("Weight")
                                .frame(width: 70, alignment: .trailing)
                            Spacer()
                        }
                        .font(.caption2.weight(.medium))
                        .foregroundStyle(theme.secondary.opacity(0.5))

                        ForEach(Array($exercise.sets.enumerated()), id: \.element.id) { index, $set in
                            HStack(spacing: 0) {
                                Text("\(index + 1)")
                                    .font(.caption)
                                    .foregroundStyle(theme.secondary.opacity(0.5))
                                    .frame(width: 32, alignment: .leading)
                                SlopNumberField("0", value: $set.reps)
                                    .foregroundStyle(theme.foreground.opacity(0.8))
                                    .multilineTextAlignment(.trailing)
                                    .frame(width: 60)
                                SlopNumberField("0", value: $set.weight)
                                    .foregroundStyle(theme.foreground.opacity(0.8))
                                    .multilineTextAlignment(.trailing)
                                    .frame(width: 70)
                                Spacer()
                                SlopInteractiveOnly {
                                    Button {
                                        withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                            $exercise.wrappedValue.sets.removeAll { $0.id == set.id }
                                        }
                                    } label: {
                                        Image(systemName: "minus.circle.fill")
                                            .font(theme.font(size: 12))
                                            .foregroundStyle(theme.secondary.opacity(0.3))
                                    }
                                    .buttonStyle(.plain)
                                }
                            }
                        }

                        SlopInteractiveOnly {
                            Button {
                                withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                    $exercise.wrappedValue.sets.append(ExerciseSet())
                                }
                            } label: {
                                Label("Add Set", systemImage: "plus")
                                    .font(.caption)
                                    .foregroundStyle(theme.secondary.opacity(0.5))
                            }
                            .buttonStyle(.plain)
                        }

                        SlopTextField("Notes", text: $exercise.notes)
                            .font(.caption)
                            .foregroundStyle(theme.secondary.opacity(0.7))
                    }
                }

                SlopInteractiveOnly {
                    Button {
                        withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                            var ex = Exercise()
                            ex.name = "New Exercise"
                            data.exercises.append(ex)
                        }
                    } label: {
                        Label("Add Exercise", systemImage: "plus")
                            .font(.caption)
                            .foregroundStyle(theme.secondary.opacity(0.6))
                    }
                    .buttonStyle(.plain)
                }

                Divider().background(theme.divider)

                HStack {
                    Text("Total Volume")
                        .foregroundStyle(theme.foreground)
                        .fontWeight(.bold)
                    Spacer()
                    Text(formattedVolume(data.totalVolume))
                        .foregroundStyle(theme.accent)
                        .fontWeight(.bold)
                        .font(.title3)
                        .contentTransition(.numericText())
                }

                VStack(alignment: .leading, spacing: 4) {
                    Text("Session Notes")
                        .font(.caption.weight(.medium))
                        .foregroundStyle(theme.secondary)
                    SlopEditable($data.sessionNotes) { value in
                        Text(value)
                            .font(.body)
                            .foregroundStyle(theme.foreground.opacity(0.8))
                    } editor: { $value in
                        TextEditor(text: $value)
                            .font(.body)
                            .foregroundStyle(theme.foreground.opacity(0.8))
                            .scrollContentBackground(.hidden)
                            .frame(minHeight: 60)
                    }
                }
            }
            .padding(24)
        }
        .background(theme.background)
    }

    // MARK: - Session Summary Card

    private var sessionSummary: some View {
        HStack(spacing: 0) {
            summaryItem(value: "\(data.totalExercises)", label: "Exercises")
            Divider().frame(height: 30).background(theme.divider)
            summaryItem(value: "\(data.totalSetsCount)", label: "Sets")
            Divider().frame(height: 30).background(theme.divider)
            summaryItem(value: formattedVolume(data.totalVolume), label: "Volume")
        }
        .padding(.vertical, 10)
        .background(theme.surface.opacity(0.5))
        .clipShape(RoundedRectangle(cornerRadius: 10))
    }

    private func summaryItem(value: String, label: String) -> some View {
        VStack(spacing: 3) {
            Text(value)
                .font(theme.font(size: 16, weight: .bold))
                .foregroundStyle(theme.accent)
                .contentTransition(.numericText())
            Text(label)
                .font(theme.font(size: 10))
                .foregroundStyle(theme.secondary)
        }
        .frame(maxWidth: .infinity)
    }

    // MARK: - Volume Bar Chart

    private var volumeBarChart: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("Volume by Exercise")
                .font(theme.font(size: 11, weight: .medium))
                .foregroundStyle(theme.secondary)

            let maxVol = data.exercises.map(\.totalVolume).max() ?? 1

            ForEach(data.exercises) { exercise in
                HStack(spacing: 8) {
                    Text(exercise.name)
                        .font(theme.font(size: 10))
                        .foregroundStyle(theme.secondary)
                        .frame(width: 80, alignment: .leading)
                        .lineLimit(1)

                    GeometryReader { geo in
                        let fraction = maxVol > 0 ? exercise.totalVolume / maxVol : 0
                        let intensity = exercise.maxWeight / max(data.exercises.map(\.maxWeight).max() ?? 1, 1)
                        Capsule()
                            .fill(theme.accent.opacity(0.4 + intensity * 0.6))
                            .frame(width: geo.size.width * min(fraction, 1.0), height: 10)
                            .animation(.spring(response: 0.3, dampingFraction: 0.7), value: fraction)
                    }
                    .frame(height: 10)

                    Text(formattedVolume(exercise.totalVolume))
                        .font(theme.mono(size: 9))
                        .foregroundStyle(theme.secondary.opacity(0.5))
                        .frame(width: 50, alignment: .trailing)
                }
            }
        }
    }

    // MARK: - Helpers

    private func formattedVolume(_ value: Double) -> String {
        String(format: "%.0f", value)
    }
}

