import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct Assignment: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Name") var name: String = ""
    @Field("Grade") var grade: Double = 0
    @Field("Weight") var weight: Double = 1.0

    var weightedGrade: Double { grade * weight }
}

@SlopData
public struct Course: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Name") var name: String = ""
    @Field("Assignments") var assignments: [Assignment] = []

    var totalWeight: Double { assignments.reduce(0) { $0 + $1.weight } }
    var weightedAverage: Double { totalWeight > 0 ? assignments.reduce(0) { $0 + $1.weightedGrade } / totalWeight : 0 }

    var letterGrade: String {
        let avg = weightedAverage
        if avg >= 97 { return "A+" }
        if avg >= 93 { return "A" }
        if avg >= 90 { return "A-" }
        if avg >= 87 { return "B+" }
        if avg >= 83 { return "B" }
        if avg >= 80 { return "B-" }
        if avg >= 77 { return "C+" }
        if avg >= 73 { return "C" }
        if avg >= 70 { return "C-" }
        if avg >= 67 { return "D+" }
        if avg >= 63 { return "D" }
        if avg >= 60 { return "D-" }
        return "F"
    }
}

@SlopData
public struct GradeTrackerData {
    @SlopKit.Section("Overview")
    @Field("Title") var title: String = "Grade Tracker"
    @Field("Semester") var semester: String = "Spring 2026"
    @Field("Target GPA") var targetGPA: Double = 3.5

    @SlopKit.Section("Courses")
    @Field("Courses") var courses: [Course] = GradeTrackerData.defaultCourses

    var overallGPA: Double {
        guard !courses.isEmpty else { return 0 }
        let total = courses.reduce(0.0) { sum, course in
            sum + gpaPoints(for: course.letterGrade)
        }
        return total / Double(courses.count)
    }

    private func gpaPoints(for letter: String) -> Double {
        switch letter {
        case "A+": return 4.0
        case "A": return 4.0
        case "A-": return 3.7
        case "B+": return 3.3
        case "B": return 3.0
        case "B-": return 2.7
        case "C+": return 2.3
        case "C": return 2.0
        case "C-": return 1.7
        case "D+": return 1.3
        case "D": return 1.0
        case "D-": return 0.7
        default: return 0.0
        }
    }
}

extension GradeTrackerData {
    static var defaultCourses: [Course] {
        func assignment(_ name: String, _ grade: Double, _ weight: Double) -> Assignment {
            var a = Assignment()
            a.name = name
            a.grade = grade
            a.weight = weight
            return a
        }

        func course(_ name: String, _ assignments: [Assignment]) -> Course {
            var c = Course()
            c.name = name
            c.assignments = assignments
            return c
        }

        return [
            course("Algorithms", [
                assignment("Midterm", 88, 1.5),
                assignment("Problem Set 1", 92, 1.0),
                assignment("Final Project", 78, 2.0),
            ]),
            course("Design Systems", [
                assignment("Case Study", 95, 1.0),
                assignment("Group Presentation", 84, 1.5),
            ]),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.grade-tracker",
    name: "Grade Tracker",
    description: "Track classes, assignments, and grades to monitor academic progress.",
    version: "1.0.0",
    width: 420, height: 600,
    minWidth: 360, minHeight: 480,
    shape: .roundedRect(radius: 18),
    theme: "cool",
    alwaysOnTop: true,
    categories: ["education"]
)
struct GradeTrackerView: View {
    @TemplateData var data: GradeTrackerData
    @Environment(\.slopTheme) private var theme

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Title", text: $data.title)
                    .font(theme.title(size: 22))
                    .foregroundStyle(theme.foreground)

                SlopTextField("Semester", text: $data.semester)
                    .font(.subheadline)
                    .foregroundStyle(theme.secondary)

                // GPA Ring centered
                HStack {
                    Spacer()
                    gpaRing
                    Spacer()
                }

                HStack {
                    Text("Target GPA")
                        .foregroundStyle(theme.secondary)
                    Spacer()
                    SlopNumberField("0.0", value: $data.targetGPA, format: "%.2f")
                        .foregroundStyle(theme.accent)
                        .fontWeight(.semibold)
                        .multilineTextAlignment(.trailing)
                        .frame(width: 60)
                }

                Divider().background(theme.divider)

                ForEach($data.courses) { $course in
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            SlopTextField("Course", text: $course.name)
                                .font(.caption.weight(.medium))
                                .foregroundStyle(theme.secondary)
                            Spacer()
                            gradeBadge(course.letterGrade)
                            Text(String(format: "%.1f%%", course.weightedAverage))
                                .font(.caption)
                                .foregroundStyle(theme.secondary.opacity(0.6))
                                .contentTransition(.numericText())
                            RemoveButton {
                                withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                    data.courses.removeAll { $0.id == course.id }
                                }
                            }
                        }

                        courseProgressBar(course)

                        ForEach($course.assignments) { $assignment in
                            HStack(spacing: 8) {
                                SlopTextField("Assignment", text: $assignment.name)
                                    .foregroundStyle(theme.foreground.opacity(0.8))
                                Spacer()
                                SlopNumberField("0", value: $assignment.grade)
                                    .foregroundStyle(theme.foreground.opacity(0.8))
                                    .multilineTextAlignment(.trailing)
                                    .frame(width: 50)
                                Text("x")
                                    .font(theme.font(size: 10))
                                    .foregroundStyle(theme.secondary.opacity(0.5))
                                SlopNumberField("1.0", value: $assignment.weight, format: "%.1f")
                                    .foregroundStyle(theme.foreground.opacity(0.8))
                                    .multilineTextAlignment(.trailing)
                                    .frame(width: 40)
                                RemoveButton {
                                    withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                        $course.wrappedValue.assignments.removeAll {
                                            $0.id == assignment.id
                                        }
                                    }
                                }
                            }
                        }

                        AddItemButton("Add Assignment") {
                            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                $course.wrappedValue.assignments.append(Assignment())
                            }
                        }
                    }
                }

                AddItemButton("Add Course") {
                    withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                        var c = Course()
                        c.name = "New Course"
                        data.courses.append(c)
                    }
                }
            }
            .padding(24)
        }
        .background(theme.background)
    }

    // MARK: - GPA Ring

    private var gpaRing: some View {
        let progress = min(data.overallGPA / 4.0, 1.0)
        let targetProgress = min(data.targetGPA / 4.0, 1.0)
        let meetsTarget = data.overallGPA >= data.targetGPA

        return ZStack {
            // Background ring
            Circle()
                .stroke(theme.surface, lineWidth: 12)
                .frame(width: 90, height: 90)

            // Target marker (thin arc)
            Circle()
                .trim(from: max(targetProgress - 0.01, 0), to: targetProgress)
                .stroke(theme.secondary.opacity(0.4), style: StrokeStyle(lineWidth: 14, lineCap: .butt))
                .frame(width: 90, height: 90)
                .rotationEffect(.degrees(-90))

            // GPA progress
            Circle()
                .trim(from: 0, to: progress)
                .stroke(
                    meetsTarget ? Color.green : theme.accent,
                    style: StrokeStyle(lineWidth: 12, lineCap: .round)
                )
                .frame(width: 90, height: 90)
                .rotationEffect(.degrees(-90))
                .animation(.spring(response: 0.3, dampingFraction: 0.7), value: progress)

            VStack(spacing: 1) {
                Text(String(format: "%.2f", data.overallGPA))
                    .font(theme.font(size: 18, weight: .bold))
                    .foregroundStyle(meetsTarget ? .green : theme.accent)
                    .contentTransition(.numericText())
                Text("GPA")
                    .font(theme.font(size: 9))
                    .foregroundStyle(theme.secondary)
            }
        }
    }

    // MARK: - Letter Grade Badge

    private func gradeColor(for letter: String) -> Color {
        if letter.hasPrefix("A") { return .green }
        if letter.hasPrefix("B") { return .blue }
        if letter.hasPrefix("C") { return .yellow }
        if letter.hasPrefix("D") { return .orange }
        return .red
    }

    private func gradeBadge(_ letter: String) -> some View {
        Text(letter)
            .font(theme.font(size: 12, weight: .bold))
            .foregroundStyle(.white)
            .padding(.horizontal, 8)
            .padding(.vertical, 3)
            .background(gradeColor(for: letter))
            .clipShape(Capsule())
    }

    // MARK: - Course Progress Bar

    private func courseProgressBar(_ course: Course) -> some View {
        ProgressBar(
            progress: min(course.weightedAverage / 100.0, 1.0),
            fillColor: gradeColor(for: course.letterGrade),
            backgroundColor: theme.surface,
            height: 6
        )
    }
}

