import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct HabitRow: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Habit") var name: String = ""
    @Field("Icon") var icon: String = "✅"
    @Field("Monday") var monday: Bool = false
    @Field("Tuesday") var tuesday: Bool = false
    @Field("Wednesday") var wednesday: Bool = false
    @Field("Thursday") var thursday: Bool = false
    @Field("Friday") var friday: Bool = false
    @Field("Saturday") var saturday: Bool = false
    @Field("Sunday") var sunday: Bool = false

    var days: [Bool] {
        [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
    }

    var completedCount: Int { days.filter { $0 }.count }

    var streak: Int {
        // Count consecutive completed days from the end of the week backwards
        var count = 0
        for day in days.reversed() {
            if day { count += 1 } else { break }
        }
        return count
    }
}

@SlopData
public struct HabitTrackerData {
    @SlopKit.Section("Overview") @Field("Title") var title: String = "Habit Tracker"
    @Field("Week Label") var weekLabel: String = "March 24 - 30, 2026"
    @SlopKit.Section("Habits") @Field("Habits") var habits: [HabitRow] = HabitTrackerData.defaultHabits

    var totalCompleted: Int { habits.reduce(0) { $0 + $1.completedCount } }
    var totalSlots: Int { habits.count * 7 }
}

extension HabitTrackerData {
    static var defaultHabits: [HabitRow] {
        func row(
            _ name: String,
            _ monday: Bool,
            _ tuesday: Bool,
            _ wednesday: Bool,
            _ thursday: Bool,
            _ friday: Bool,
            _ saturday: Bool,
            _ sunday: Bool
        ) -> HabitRow {
            var value = HabitRow()
            value.name = name
            value.monday = monday
            value.tuesday = tuesday
            value.wednesday = wednesday
            value.thursday = thursday
            value.friday = friday
            value.saturday = saturday
            value.sunday = sunday
            return value
        }

        return [
            row("Exercise", true, true, true, false, false, false, false),
            row("Reading", true, true, true, true, true, false, false),
            row("Meditation", true, false, true, false, false, false, false),
            row("Journaling", true, true, true, true, false, false, false),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.habit-tracker",
    name: "Habit Tracker",
    description: "Build a streak board for daily habits and see your consistency over time.",
    version: "1.0.0",
    width: 430, height: 520,
    minWidth: 360, minHeight: 400,
    shape: .roundedRect(radius: 20),
    theme: "terminal",
    alwaysOnTop: true,
    categories: ["popular", "personal"]
)
struct HabitTrackerView: View {
    @TemplateData var data: HabitTrackerData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    private let dayLabels = ["M", "T", "W", "T", "F", "S", "S"]

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 18) {
                SlopTextField("Title", text: $data.title)
                    .font(theme.title(size: 24))
                    .foregroundStyle(theme.foreground)
                SlopTextField("Week label", text: $data.weekLabel)
                    .font(theme.mono(size: 12, weight: .medium))
                    .foregroundStyle(theme.secondary)

                // Empty state
                if data.habits.isEmpty {
                    EmptyState(
                        icon: "checklist",
                        title: "No habits yet",
                        subtitle: "Add a habit to start tracking"
                    )
                } else {
                    VStack(alignment: .leading, spacing: 10) {
                        // Header row
                        HStack {
                            Text("Habit")
                                .frame(maxWidth: .infinity, alignment: .leading)
                            ForEach(dayLabels, id: \.self) { day in
                                Text(day)
                                    .frame(width: 22)
                            }
                            Text("Score")
                                .frame(width: 42, alignment: .trailing)
                        }
                        .font(theme.mono(size: 10, weight: .bold))
                        .foregroundStyle(theme.secondary)

                        ForEach($data.habits) { $habit in
                            HStack {
                                SlopEmojiPicker($habit.icon)
                                    .activityEmojis()
                                    .font(.system(size: 14))

                                SlopTextField("Habit", text: $habit.name)
                                    .foregroundStyle(theme.foreground)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                if renderTarget == .interactive {
                                    dayToggle($habit.monday)
                                    dayToggle($habit.tuesday)
                                    dayToggle($habit.wednesday)
                                    dayToggle($habit.thursday)
                                    dayToggle($habit.friday)
                                    dayToggle($habit.saturday)
                                    dayToggle($habit.sunday)
                                } else {
                                    ForEach(Array(habit.days.enumerated()), id: \.offset) { _, isComplete in
                                        Circle()
                                            .fill(isComplete ? theme.accent : theme.surface)
                                            .overlay {
                                                if isComplete {
                                                    Image(systemName: "checkmark")
                                                        .font(theme.font(size: 8, weight: .bold))
                                                        .foregroundStyle(theme.background)
                                                }
                                            }
                                            .frame(width: 16, height: 16)
                                            .frame(width: 22)
                                    }
                                }
                                Text("\(habit.completedCount)/7")
                                    .foregroundStyle(theme.accent)
                                    .contentTransition(.numericText())
                                    .frame(width: 42, alignment: .trailing)
                                RemoveButton {
                                    withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                        data.habits.removeAll { $0.id == habit.id }
                                    }
                                }
                            }
                            .font(theme.font(size: 13, weight: .medium))
                            .padding(.vertical, 4)
                        }

                        // Streak badges
                        streakBadges
                    }

                    AddItemButton("Add Habit") {
                        withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                            data.habits.append(HabitRow())
                        }
                    }
                }

                ThemeDivider()

                // Heat map
                heatMap

                weeklyScore
            }
            .padding(24)
        }
        .background(theme.background)
    }

    // MARK: - Streak Badges

    private var streakBadges: some View {
        let activeStreaks = data.habits.filter { $0.streak > 0 }
        return Group {
            if !activeStreaks.isEmpty {
                HStack(spacing: 6) {
                    ForEach(activeStreaks) { habit in
                        HStack(spacing: 3) {
                            Image(systemName: "flame.fill")
                                .font(theme.font(size: 9))
                                .foregroundStyle(.orange)
                            Text("\(habit.name) \(habit.streak)d")
                                .font(theme.font(size: 10, weight: .medium))
                                .foregroundStyle(theme.foreground.opacity(0.7))
                        }
                        .padding(.horizontal, 6)
                        .padding(.vertical, 3)
                        .background(theme.surface)
                        .clipShape(Capsule())
                    }
                }
                .padding(.top, 4)
            }
        }
    }

    // MARK: - Heat Map

    private var heatMap: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("This Week")
                .font(theme.font(size: 11, weight: .medium))
                .foregroundStyle(theme.secondary)

            ForEach(data.habits) { habit in
                HStack(spacing: 3) {
                    Text(habit.name)
                        .font(theme.font(size: 9))
                        .foregroundStyle(theme.secondary.opacity(0.6))
                        .frame(width: 70, alignment: .leading)
                        .lineLimit(1)

                    ForEach(Array(habit.days.enumerated()), id: \.offset) { _, isComplete in
                        RoundedRectangle(cornerRadius: 2)
                            .fill(isComplete ? theme.accent : theme.surface)
                            .frame(width: 14, height: 14)
                    }
                }
            }
        }
    }

    // MARK: - Day Toggle

    private func dayToggle(_ value: Binding<Bool>) -> some View {
        Button {
            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                value.wrappedValue.toggle()
            }
        } label: {
            Circle()
                .fill(value.wrappedValue ? theme.accent : theme.surface)
                .overlay {
                    if value.wrappedValue {
                        Image(systemName: "checkmark")
                            .font(theme.font(size: 8, weight: .bold))
                            .foregroundStyle(theme.background)
                    }
                }
                .frame(width: 16, height: 16)
                .frame(width: 22)
                .scaleEffect(value.wrappedValue ? 1.0 : 0.85)
                .animation(.spring(response: 0.3, dampingFraction: 0.7), value: value.wrappedValue)
        }
        .buttonStyle(.plain)
    }

    // MARK: - Weekly Score

    private var weeklyScore: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Text("Weekly Score")
                    .foregroundStyle(theme.secondary)
                Spacer()
                Text("\(data.totalCompleted) / \(data.totalSlots)")
                    .font(theme.font(size: 16, weight: .bold))
                    .foregroundStyle(theme.accent)
                    .contentTransition(.numericText())
            }

            ProgressBar(
                progress: data.totalSlots == 0 ? 0 : Double(data.totalCompleted) / Double(data.totalSlots),
                fillColor: theme.accent,
                backgroundColor: theme.surface,
                height: 10
            )
        }
    }
}

