import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct InvoiceLineItem: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Description") var description: String = ""
    @Field("Hours") var hours: Double = 1
    @Field("Rate") var rate: Double = 150

    var subtotal: Double { hours * rate }
}

@SlopData
public struct InvoiceData {
    @SlopKit.Section("Overview") @Field("Document Title") var title: String = "Q1 Invoice"
    @Field("Status", options: ["Draft", "Outstanding", "Paid"]) var status: String = "Outstanding"
    @Field("Currency", options: ["USD", "EUR", "GBP"]) var currency: String = "USD"
    @Field("Invoice Number") var invoiceNumber: String = "INV-2026-042"
    @Field("Invoice Date") var invoiceDate: Date = .now
    @Field("Due Date") var dueDate: Date = Calendar.current.date(byAdding: .day, value: 30, to: .now) ?? .now
    @Field("Tax Rate") var taxRate: Double = 0.08

    @SlopKit.Section("Company") @Field("Company Name") var companyName: String = "Acme Design Co."
    @Field("Street") var companyStreet: String = "123 Creative Blvd"
    @Field("City") var companyCity: String = "San Francisco, CA 94102"
    @Field("Client") var clientName: String = "Globex Corp"

    @SlopKit.Section("Items") @Field("Line Items") var items: [InvoiceLineItem] = InvoiceData.defaultItems

    @SlopKit.Section("Notes") @Field("Notes") var notes: String = "Thank you for your business."

    var subtotal: Double { items.reduce(0) { $0 + $1.subtotal } }
    var tax: Double { subtotal * taxRate }
    var total: Double { subtotal + tax }
}

extension InvoiceData {
    static var defaultItems: [InvoiceLineItem] {
        func item(_ description: String, _ hours: Double, _ rate: Double) -> InvoiceLineItem {
            var value = InvoiceLineItem()
            value.description = description
            value.hours = hours
            value.rate = rate
            return value
        }

        return [
            item("Brand strategy workshop", 12, 175),
            item("UI system audit", 16, 150),
            item("Prototype iteration", 10, 165),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.invoice",
    name: "Invoice",
    description: "Draft a client invoice with line items, totals, and payment details.",
    version: "1.0.0",
    width: 440, height: 620,
    minWidth: 380, minHeight: 460,
    shape: .roundedRect(radius: 20),
    theme: "paper",
    alwaysOnTop: true,
    categories: ["business"]
)
struct InvoiceView: View {
    @TemplateData var data: InvoiceData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 18) {
                HStack(alignment: .top) {
                    VStack(alignment: .leading, spacing: 6) {
                        SlopTextField("Company", text: $data.companyName)
                            .font(theme.title(size: 24))
                            .foregroundStyle(theme.foreground)
                        SlopTextField("Street", text: $data.companyStreet)
                            .foregroundStyle(theme.secondary)
                        SlopTextField("City", text: $data.companyCity)
                            .foregroundStyle(theme.secondary)
                        HStack(spacing: 4) {
                            Text("Client:")
                                .foregroundStyle(theme.secondary)
                            SlopTextField("Client", text: $data.clientName)
                                .foregroundStyle(theme.secondary)
                        }
                        .padding(.top, 8)
                    }

                    Spacer()

                    VStack(alignment: .trailing, spacing: 6) {
                        SlopTextField("Title", text: $data.title)
                            .font(theme.font(size: 16, weight: .semibold))
                            .foregroundStyle(theme.foreground)
                            .multilineTextAlignment(.trailing)

                        if renderTarget == .interactive {
                            Picker("Status", selection: $data.status) {
                                Text("Draft").tag("Draft")
                                Text("Outstanding").tag("Outstanding")
                                Text("Paid").tag("Paid")
                            }
                            .labelsHidden()
                            .pickerStyle(.menu)
                        } else {
                            StatusBadge(data.status)
                        }

                        HStack(spacing: 4) {
                            Text("Invoice #")
                                .foregroundStyle(theme.secondary)
                            SlopTextField("#", text: $data.invoiceNumber)
                                .foregroundStyle(theme.foreground)
                                .multilineTextAlignment(.trailing)
                                .frame(width: 100)
                        }
                        .font(theme.font(size: 12))

                        if renderTarget == .interactive {
                            DatePicker("Issued", selection: $data.invoiceDate, displayedComponents: .date)
                                .font(theme.font(size: 12))
                                .foregroundStyle(theme.secondary)
                            DatePicker("Due", selection: $data.dueDate, displayedComponents: .date)
                                .font(theme.font(size: 12))
                                .foregroundStyle(theme.secondary)
                        } else {
                            metaRow("Issued", dateStringAbbreviated(data.invoiceDate))
                            metaRow("Due", dateStringAbbreviated(data.dueDate))
                        }
                    }
                }

                ThemeDivider()

                VStack(alignment: .leading, spacing: 10) {
                    HStack {
                        tableHeader("Item", alignment: .leading)
                        Spacer()
                        tableHeader("Hours", width: 60)
                        tableHeader("Rate", width: 72)
                        tableHeader("Subtotal", width: 88)
                    }

                    ForEach($data.items) { $item in
                        HStack(alignment: .top) {
                            SlopTextField("Description", text: $item.description)
                                .foregroundStyle(theme.foreground)
                            Spacer()
                            SlopNumberField("0", value: $item.hours, format: "%.0f")
                                .foregroundStyle(theme.foreground)
                                .multilineTextAlignment(.trailing)
                                .frame(width: 60)
                            SlopNumberField("0", value: $item.rate)
                                .foregroundStyle(theme.foreground)
                                .multilineTextAlignment(.trailing)
                                .frame(width: 72)
                            Text(currency(item.subtotal))
                                .font(theme.font(size: 13, weight: .semibold))
                                .foregroundStyle(theme.foreground)
                                .frame(width: 68, alignment: .trailing)
                            RemoveButton {
                                withAnimation { data.items.removeAll { $0.id == item.id } }
                            }
                        }
                        .padding(.vertical, 8)
                        .overlay(alignment: .bottom) {
                            Rectangle()
                                .fill(theme.divider.opacity(0.5))
                                .frame(height: 1)
                        }
                    }

                    AddItemButton("Add Line Item") {
                        withAnimation { data.items.append(InvoiceLineItem()) }
                    }
                }

                VStack(alignment: .trailing, spacing: 10) {
                    SummaryRow(label: "Subtotal", value: currency(data.subtotal))
                    if renderTarget == .interactive {
                        HStack(spacing: 20) {
                            Text("Tax")
                                .foregroundStyle(theme.secondary)
                            TextField("0", value: $data.taxRate, format: .percent)
                                .foregroundStyle(theme.foreground)
                                .textFieldStyle(.plain)
                                .multilineTextAlignment(.trailing)
                                .frame(width: 60)
                        }
                    } else {
                        SummaryRow(label: "Tax", value: "\(Int(data.taxRate * 100))%")
                    }
                    SummaryRow(
                        label: "Total",
                        value: currency(data.total),
                        valueColor: theme.accent,
                        isBold: true
                    )
                }
                .frame(maxWidth: .infinity, alignment: .trailing)

                ThemeDivider()

                VStack(alignment: .leading, spacing: 8) {
                    SectionHeader("Payment Notes")
                    SlopEditable($data.notes) { value in
                        Text(value)
                            .foregroundStyle(theme.foreground.opacity(0.85))
                            .fixedSize(horizontal: false, vertical: true)
                    } editor: { $value in
                        TextEditor(text: $value)
                            .foregroundStyle(theme.foreground.opacity(0.85))
                            .scrollContentBackground(.hidden)
                            .font(theme.font(size: 13))
                            .frame(minHeight: 40)
                    }
                }
            }
            .padding(26)
        }
        .background(theme.background)
    }

    // MARK: - Helpers

    private func metaRow(_ label: String, _ value: String) -> some View {
        HStack(spacing: 12) {
            Text(label)
                .foregroundStyle(theme.secondary)
            Text(value)
                .foregroundStyle(theme.foreground)
        }
        .font(theme.font(size: 12))
    }

    private func tableHeader(_ label: String, alignment: Alignment = .trailing, width: CGFloat? = nil) -> some View {
        Text(label.uppercased())
            .font(theme.mono(size: 10, weight: .bold))
            .foregroundStyle(theme.secondary)
            .frame(width: width, alignment: alignment)
    }

    private func currency(_ value: Double) -> String {
        formatCurrency(value, code: data.currency)
    }
}

