import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct StandupBullet: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Item") var title: String = ""
}

@SlopData
public struct StandupData {
    @SlopKit.Section("Overview") @Field("Title") var title: String = "Team Standup"
    @Field("Meeting Date") var meetingDate: Date = .now
    @Field("Notes") var notes: String = "Sprint ends Friday. Demo at 3pm."

    @SlopKit.Section("Done") @Field("Done Items") var done: [StandupBullet] = StandupData.defaultDone
    @SlopKit.Section("Today") @Field("Today Items") var today: [StandupBullet] = StandupData.defaultToday
    @SlopKit.Section("Blockers") @Field("Blockers") var blockers: [StandupBullet] = StandupData.defaultBlockers
}

extension StandupData {
    static var defaultDone: [StandupBullet] {
        bullets([
            "Deploy auth service",
            "Review PR #342",
            "Update API docs",
        ])
    }

    static var defaultToday: [StandupBullet] {
        bullets([
            "Migrate database schema",
            "Write integration tests",
            "Design settings page",
        ])
    }

    static var defaultBlockers: [StandupBullet] {
        bullets([
            "Waiting on DevOps for staging env",
            "CI pipeline flaky on ARM runners",
        ])
    }

    private static func bullets(_ titles: [String]) -> [StandupBullet] {
        titles.map { title in
            var value = StandupBullet()
            value.title = title
            return value
        }
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.team-standup",
    name: "Team Standup",
    description: "Capture yesterday, today, and blockers for a crisp daily standup note.",
    version: "1.0.0",
    width: 520, height: 500,
    minWidth: 420, minHeight: 360,
    shape: .roundedRect(radius: 18),
    theme: "ocean",
    alwaysOnTop: true,
    categories: ["productivity"]
)
struct StandupView: View {
    @TemplateData var data: StandupData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    private static func makeDate(_ y: Int, _ m: Int, _ d: Int) -> Date {
        Calendar.current.date(from: DateComponents(year: y, month: m, day: d)) ?? .now
    }

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Title", text: $data.title)
                    .font(theme.title(size: 24))
                    .foregroundStyle(theme.foreground)
                SlopEditable($data.meetingDate) { value in
                    Text(value, style: .date)
                        .font(theme.mono(size: 12, weight: .medium))
                        .foregroundStyle(theme.secondary)
                } editor: { $value in
                    DatePicker("", selection: $value, displayedComponents: .date)
                        .labelsHidden()
                }

                HStack(alignment: .top, spacing: 14) {
                    columnView("Done", items: $data.done, tint: theme.accent)
                    columnView("Today", items: $data.today, tint: Color.orange)
                    columnView("Blockers", items: $data.blockers, tint: Color.red.opacity(0.8))
                }

                Divider().background(theme.divider)

                VStack(alignment: .leading, spacing: 0) {
                    SlopEditable($data.notes) { value in
                        Text(value)
                    } editor: { $notes in
                        TextEditor(text: $notes)
                            .scrollContentBackground(.hidden)
                    }
                    .foregroundStyle(theme.secondary)
                    .font(theme.font(size: 13))
                    .frame(minHeight: 40)
                }
            }
            .padding(24)
        }
        .background(theme.background)
    }

    private func columnView(_ title: String, items: Binding<[StandupBullet]>, tint: Color) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title.uppercased())
                .font(theme.mono(size: 10, weight: .bold))
                .foregroundStyle(tint)
            ForEach(items) { $item in
                HStack(alignment: .top, spacing: 8) {
                    Circle()
                        .fill(tint)
                        .frame(width: 7, height: 7)
                        .padding(.top, 5)
                    SlopTextField("Item", text: $item.title)
                        .foregroundStyle(theme.foreground)
                    SlopInteractiveOnly {
                        Button {
                            withAnimation { items.wrappedValue.removeAll { $0.id == item.id } }
                        } label: {
                            Image(systemName: "minus.circle.fill")
                                .font(theme.font(size: 10))
                                .foregroundStyle(theme.secondary.opacity(0.3))
                        }
                        .buttonStyle(.plain)
                    }
                }
                .font(theme.font(size: 13, weight: .medium))
            }

            SlopInteractiveOnly {
                Button {
                    withAnimation { items.wrappedValue.append(StandupBullet()) }
                } label: {
                    Label("Add", systemImage: "plus")
                        .font(.caption)
                        .foregroundStyle(theme.secondary.opacity(0.5))
                }
                .buttonStyle(.plain)
            }

            Spacer(minLength: 0)
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .topLeading)
        .background(
            RoundedRectangle(cornerRadius: 14)
                .fill(theme.surface)
        )
    }
}

