import Foundation
import SwiftUI
import SlopKit

// MARK: - Data Model

@SlopData
public struct Subscription: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Name") var name: String = ""
    @Field("Amount") var amount: Double = 0
    @Field("Frequency", options: ["Monthly", "Yearly", "Weekly"]) var frequency: String = "Monthly"
    @Field("Renewal Date") var renewalDate: Date = .now
    @Field("Color") var color: String = "#4A9EFF"
    @Field("Category", options: ["Entertainment", "Productivity", "Cloud", "Other"]) var category: String = "Other"
}

@SlopData
public struct SubscriptionTrackerData {
    @Field("Title") var title: String = "Subscriptions"
    @Field("Subscriptions") var subscriptions: [Subscription] = SubscriptionTrackerData.defaultSubscriptions

    var monthlyTotal: Double {
        subscriptions.reduce(0) { total, sub in
            total + monthlyAmount(for: sub)
        }
    }

    var yearlyTotal: Double { monthlyTotal * 12 }

    var categoryBreakdown: [(category: String, total: Double)] {
        let categories = ["Entertainment", "Productivity", "Cloud", "Other"]
        return categories.compactMap { cat in
            let total = subscriptions
                .filter { $0.category == cat }
                .reduce(0) { $0 + monthlyAmount(for: $1) }
            return total > 0 ? (category: cat, total: total) : nil
        }
    }

    func monthlyAmount(for sub: Subscription) -> Double {
        switch sub.frequency {
        case "Yearly": return sub.amount / 12
        case "Weekly": return sub.amount * (52.0 / 12.0)
        default: return sub.amount
        }
    }
}

extension SubscriptionTrackerData {
    static var defaultSubscriptions: [Subscription] {
        func sub(_ name: String, _ amount: Double, _ frequency: String, _ year: Int, _ month: Int, _ day: Int, _ color: String, _ category: String) -> Subscription {
            var s = Subscription()
            s.name = name
            s.amount = amount
            s.frequency = frequency
            s.renewalDate = makeDate(year, month, day)
            s.color = color
            s.category = category
            return s
        }

        return [
            sub("Netflix", 15.99, "Monthly", 2026, 4, 20, "#E50914", "Entertainment"),
            sub("Spotify", 9.99, "Monthly", 2026, 4, 18, "#1DB954", "Entertainment"),
            sub("iCloud", 2.99, "Monthly", 2026, 4, 12, "#3693F5", "Cloud"),
            sub("GitHub", 4, "Monthly", 2026, 4, 25, "#8957E5", "Productivity"),
            sub("Adobe CC", 54.99, "Monthly", 2026, 5, 1, "#FF0000", "Productivity"),
        ]
    }

    private static func makeDate(_ y: Int, _ m: Int, _ d: Int) -> Date {
        Calendar.current.date(from: DateComponents(year: y, month: m, day: d)) ?? .now
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.subscription-tracker",
    name: "Subscription Tracker",
    description: "Monitor recurring subscriptions, renewal dates, and monthly spend.",
    version: "1.0.0",
    width: 360, height: 520,
    minWidth: 320, minHeight: 400,
    shape: .roundedRect(radius: 18),
    alwaysOnTop: true,
    categories: ["finance"]
)
struct SubscriptionTrackerView: View {
    @TemplateData var data: SubscriptionTrackerData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Title", text: $data.title)
                    .font(theme.title(size: 22))
                    .foregroundStyle(theme.foreground)

                Divider().background(theme.divider)

                // Summary card
                summaryCard

                Divider().background(theme.divider)

                // Subscription list sorted by next renewal
                ForEach($data.subscriptions.sorted(by: { daysUntilRenewal($0.wrappedValue) < daysUntilRenewal($1.wrappedValue) })) { $sub in
                    HStack(spacing: 10) {
                        Circle()
                            .fill(colorFromHex(sub.color))
                            .frame(width: 10, height: 10)

                        VStack(alignment: .leading, spacing: 2) {
                            SlopTextField("Name", text: $sub.name)
                                .font(theme.font(size: 13, weight: .medium))
                                .foregroundStyle(theme.foreground)
                            HStack(spacing: 4) {
                                SlopEditable($sub.renewalDate) { value in
                                    Text(value, style: .date)
                                        .font(theme.font(size: 10))
                                        .foregroundStyle(theme.secondary)
                                } editor: { $value in
                                    DatePicker("", selection: $value, displayedComponents: .date)
                                        .labelsHidden()
                                }
                                let days = daysUntilRenewal(sub)
                                Text(days == 0 ? "today" : days == 1 ? "1 day" : "\(days) days")
                                    .font(theme.font(size: 10, weight: .medium))
                                    .foregroundStyle(days <= 3 ? Color.red : theme.accent)
                            }
                            if renderTarget == .interactive {
                                Picker("", selection: $sub.category) {
                                    Text("Entertainment").tag("Entertainment")
                                    Text("Productivity").tag("Productivity")
                                    Text("Cloud").tag("Cloud")
                                    Text("Other").tag("Other")
                                }
                                .labelsHidden()
                                .pickerStyle(.menu)
                                .controlSize(.mini)
                            } else {
                                Text(sub.category)
                                    .font(theme.font(size: 10))
                                    .foregroundStyle(theme.secondary)
                            }
                        }

                        Spacer()

                        VStack(alignment: .trailing, spacing: 2) {
                            HStack(spacing: 2) {
                                Text("$")
                                    .font(theme.font(size: 11))
                                    .foregroundStyle(theme.secondary)
                                SlopNumberField("0", value: $sub.amount)
                                    .font(theme.font(size: 13, weight: .semibold))
                                    .foregroundStyle(theme.foreground)
                                    .multilineTextAlignment(.trailing)
                                    .frame(width: 55)
                            }
                            SlopInteractiveOnly {
                                Picker("", selection: $sub.frequency) {
                                    Text("Monthly").tag("Monthly")
                                    Text("Yearly").tag("Yearly")
                                    Text("Weekly").tag("Weekly")
                                }
                                .labelsHidden()
                                .controlSize(.mini)
                            }
                            if renderTarget != .interactive {
                                Text(sub.frequency)
                                    .font(theme.font(size: 10))
                                    .foregroundStyle(theme.secondary)
                                    .padding(.horizontal, 6)
                                    .padding(.vertical, 1)
                                    .background(
                                        Capsule().fill(theme.surface)
                                    )
                            }
                        }

                        SlopInteractiveOnly {
                            Button {
                                withAnimation {
                                    data.subscriptions.removeAll { $0.id == sub.id }
                                }
                            } label: {
                                Image(systemName: "minus.circle.fill")
                                    .font(theme.font(size: 12))
                                    .foregroundStyle(theme.secondary.opacity(0.3))
                            }
                            .buttonStyle(.plain)
                        }
                    }
                    .padding(.vertical, 4)
                }

                SlopInteractiveOnly {
                    Button {
                        withAnimation {
                            data.subscriptions.append(Subscription())
                        }
                    } label: {
                        Label("Add Subscription", systemImage: "plus")
                            .font(.caption)
                            .foregroundStyle(theme.secondary.opacity(0.6))
                    }
                    .buttonStyle(.plain)
                }

                Divider().background(theme.divider)

                // Category breakdown
                categoryBreakdownSection
            }
            .padding(24)
        }
        .background(theme.background)
    }

    // MARK: - Shared Components

    private var summaryCard: some View {
        HStack(spacing: 0) {
            VStack(spacing: 4) {
                Text("Monthly")
                    .font(theme.font(size: 10, weight: .medium))
                    .foregroundStyle(theme.secondary)
                Text("$\(String(format: "%.2f", data.monthlyTotal))")
                    .font(theme.font(size: 18, weight: .bold))
                    .foregroundStyle(theme.accent)
            }
            .frame(maxWidth: .infinity)

            Divider()
                .frame(height: 36)
                .background(theme.divider)

            VStack(spacing: 4) {
                Text("Yearly")
                    .font(theme.font(size: 10, weight: .medium))
                    .foregroundStyle(theme.secondary)
                Text("$\(String(format: "%.2f", data.yearlyTotal))")
                    .font(theme.font(size: 18, weight: .bold))
                    .foregroundStyle(theme.foreground)
            }
            .frame(maxWidth: .infinity)
        }
        .padding(.vertical, 12)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(theme.surface)
        )
    }

    private var categoryBreakdownSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("By Category")
                .font(.caption.weight(.medium))
                .foregroundStyle(theme.secondary)

            ForEach(data.categoryBreakdown, id: \.category) { entry in
                HStack(spacing: 8) {
                    Text(entry.category)
                        .font(.caption)
                        .foregroundStyle(theme.foreground.opacity(0.8))
                        .frame(width: 90, alignment: .leading)
                    GeometryReader { geo in
                        let fraction = data.monthlyTotal > 0 ? entry.total / data.monthlyTotal : 0
                        ZStack(alignment: .leading) {
                            Capsule()
                                .fill(theme.surface)
                                .frame(height: 6)
                            Capsule()
                                .fill(theme.accent)
                                .frame(width: geo.size.width * fraction, height: 6)
                        }
                    }
                    .frame(height: 6)
                    Text("$\(String(format: "%.2f", entry.total))")
                        .font(.caption)
                        .foregroundStyle(theme.secondary.opacity(0.6))
                        .frame(width: 60, alignment: .trailing)
                }
            }
        }
    }

    // MARK: - Helpers

    private func daysUntilRenewal(_ sub: Subscription) -> Int {
        let days = Calendar.current.dateComponents([.day], from: Calendar.current.startOfDay(for: Date()), to: Calendar.current.startOfDay(for: sub.renewalDate)).day ?? 0
        return max(days, 0)
    }
}
