import Foundation
import SwiftUI
import SlopKit

@SlopData
public struct TodoTask: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Task") var title: String = ""
    @Field("Done") var isDone: Bool = false
}

@SlopData
public struct TodoListData {
    @SlopKit.Section("Overview") @Field("Title") var title: String = "Sprint Tasks"
    @Field("Subtitle") var subtitle: String = "To Do"
    @Field("Owner") var owner: String = "Product Team"
    @Field("Notes") var notes: String = "Blocked on DevOps review for the CI pipeline."
    @SlopKit.Section("Tasks") @Field("Tasks") var tasks: [TodoTask] = TodoListData.defaultTasks

    var completedCount: Int { tasks.filter(\.isDone).count }
    var remainingCount: Int { max(tasks.count - completedCount, 0) }
    var completionRatio: Double {
        guard !tasks.isEmpty else { return 0 }
        return Double(completedCount) / Double(tasks.count)
    }
}

extension TodoListData {
    static var defaultTasks: [TodoTask] {
        func task(_ title: String, _ isDone: Bool) -> TodoTask {
            var value = TodoTask()
            value.title = title
            value.isDone = isDone
            return value
        }

        return [
            task("Design landing page", true),
            task("Write API endpoints", true),
            task("Set up CI pipeline", false),
            task("Write integration tests", false),
            task("Deploy to staging", false),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.todo-list",
    name: "Todo List",
    description: "Manage a straightforward checklist with priorities and completion state.",
    version: "1.0.0",
    width: 360, height: 560,
    minWidth: 320, minHeight: 420,
    shape: .roundedRect(radius: 20),
    theme: "cool",
    alwaysOnTop: true,
    categories: ["popular", "work"]
)
struct TodoListView: View {
    @TemplateData var data: TodoListData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 18) {
                VStack(alignment: .leading, spacing: 6) {
                    SlopTextField("Title", text: $data.title)
                        .font(theme.title(size: 24))
                        .foregroundStyle(theme.foreground)
                    SlopTextField("Subtitle", text: $data.subtitle)
                        .font(theme.font(size: 13, weight: .medium))
                        .foregroundStyle(theme.secondary)
                    SlopTextField("Owner", text: $data.owner)
                        .font(theme.mono(size: 10, weight: .bold))
                        .foregroundStyle(theme.accent)
                }

                progressCard

                ThemeDivider()

                VStack(alignment: .leading, spacing: 12) {
                    ForEach($data.tasks) { $task in
                        ChecklistItem(
                            title: $task.title,
                            isChecked: $task.isDone,
                            placeholder: "Task",
                            onRemove: {
                                withAnimation { data.tasks.removeAll { $0.id == task.id } }
                            }
                        )
                    }

                    AddItemButton("Add Task") {
                        withAnimation { data.tasks.append(TodoTask()) }
                    }
                }

                ThemeDivider()

                VStack(alignment: .leading, spacing: 8) {
                    Text("Notes")
                        .font(theme.mono(size: 10, weight: .bold))
                        .foregroundStyle(theme.secondary)
                    SlopEditable($data.notes) { value in
                        Text(value)
                    } editor: { $notes in
                        TextEditor(text: $notes)
                            .scrollContentBackground(.hidden)
                    }
                    .foregroundStyle(theme.foreground.opacity(0.85))
                    .font(theme.font(size: 13))
                    .frame(minHeight: 60)
                }
            }
            .padding(24)
        }
        .background(theme.background)
    }

    private var progressCard: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                MetricPill("\(data.completedCount) done", tint: theme.accent)
                MetricPill("\(data.remainingCount) left", tint: theme.secondary)
                Spacer()
            }

            ProgressBar(
                progress: data.completionRatio,
                fillColor: theme.accent,
                backgroundColor: theme.surface,
                height: 10
            )
        }
    }
}

