import Foundation
import SwiftUI
import SlopKit

// MARK: - Data Model

@SlopData
public struct FavoriteConversion: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("From Unit") var fromUnit: String = ""
    @Field("To Unit") var toUnit: String = ""
    @Field("Category") var category: String = "Length"
}

@SlopData
public struct UnitConverterData {
    @Field("Category", options: ["Length", "Weight", "Temperature", "Volume"]) var category: String = "Length"
    @Field("From Unit") var fromUnit: String = "m"
    @Field("To Unit") var toUnit: String = "ft"
    @Field("Input Value") var inputValue: Double = 1.0
    @Field("Favorites") var favorites: [FavoriteConversion] = []
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.unit-converter",
    name: "Unit Converter",
    description: "Convert between common units instantly in a tiny utility window.",
    version: "1.0.0",
    width: 300, height: 400,
    shape: .roundedRect(radius: 18),
    alwaysOnTop: true,
    categories: ["work"]
)
struct UnitConverterView: View {
    @TemplateData var data: UnitConverterData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    var body: some View {
        SlopContent {
            VStack(alignment: .leading, spacing: 14) {
                // Title
                Text("Unit Converter")
                    .font(theme.title(size: 20))
                    .foregroundStyle(theme.foreground)

                if renderTarget == .interactive {
                    // Category tabs
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 6) {
                            ForEach(allCategories, id: \.self) { cat in
                                Button {
                                    withAnimation(.easeInOut(duration: 0.2)) {
                                        data.category = cat
                                        let units = units(for: cat)
                                        data.fromUnit = units.first ?? ""
                                        data.toUnit = units.count > 1 ? units[1] : (units.first ?? "")
                                    }
                                } label: {
                                    Text(cat)
                                        .font(theme.font(size: 12, weight: data.category == cat ? .semibold : .regular))
                                        .foregroundStyle(data.category == cat ? theme.background : theme.foreground)
                                        .padding(.horizontal, 10)
                                        .padding(.vertical, 5)
                                        .background(
                                            Capsule()
                                                .fill(data.category == cat ? theme.accent : theme.surface)
                                        )
                                }
                                .buttonStyle(.plain)
                            }
                        }
                    }
                } else {
                    Text(data.category)
                        .font(.caption.weight(.medium))
                        .foregroundStyle(theme.secondary)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)
                        .background(
                            Capsule()
                                .fill(theme.surface)
                        )
                }

                Divider().background(theme.divider)

                if renderTarget == .interactive {
                    interactiveConversionFields
                } else {
                    exportConversionResult
                }

                // Favorites section
                if !data.favorites.isEmpty {
                    Divider().background(theme.divider)

                    VStack(alignment: .leading, spacing: renderTarget == .interactive ? 8 : 6) {
                        Text(renderTarget == .interactive ? "Favorites" : "Saved Conversions")
                            .font(.caption.weight(.medium))
                            .foregroundStyle(theme.secondary)

                        ForEach(data.favorites) { fav in
                            HStack(spacing: 6) {
                                if renderTarget == .interactive {
                                    Button {
                                        withAnimation(.easeInOut(duration: 0.2)) {
                                            data.category = fav.category
                                            data.fromUnit = fav.fromUnit
                                            data.toUnit = fav.toUnit
                                        }
                                    } label: {
                                        favoriteLabel(fav)
                                    }
                                    .buttonStyle(.plain)
                                } else {
                                    favoriteLabel(fav)
                                }

                                Spacer()

                                SlopInteractiveOnly {
                                    Button {
                                        withAnimation {
                                            data.favorites.removeAll { $0.id == fav.id }
                                        }
                                    } label: {
                                        Image(systemName: "minus.circle.fill")
                                            .font(theme.font(size: 11))
                                            .foregroundStyle(theme.secondary.opacity(0.3))
                                    }
                                    .buttonStyle(.plain)
                                }
                            }
                            .padding(.vertical, renderTarget == .interactive ? 2 : 0)
                        }
                    }
                }
            }
            .padding(20)
        }
        .background(theme.background)
    }

    // MARK: - Interactive Conversion Fields

    private var interactiveConversionFields: some View {
        VStack(alignment: .leading, spacing: 14) {
            // From field
            VStack(alignment: .leading, spacing: 6) {
                Text("From")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(theme.secondary)

                HStack(spacing: 8) {
                    TextField("0", value: $data.inputValue, format: .number)
                        .font(theme.title(size: 24, weight: .semibold))
                        .foregroundStyle(theme.foreground)
                        .textFieldStyle(.plain)
                        .frame(maxWidth: .infinity, alignment: .leading)

                    Picker("", selection: $data.fromUnit) {
                        ForEach(currentUnits, id: \.self) { unit in
                            Text(unit).tag(unit)
                        }
                    }
                    .labelsHidden()
                    .frame(width: 70)
                }
                .padding(10)
                .background(
                    RoundedRectangle(cornerRadius: 10)
                        .fill(theme.surface)
                )
            }

            // Swap button
            HStack {
                Spacer()
                Button {
                    withAnimation(.easeInOut(duration: 0.2)) {
                        let tmp = data.fromUnit
                        data.fromUnit = data.toUnit
                        data.toUnit = tmp
                    }
                } label: {
                    Image(systemName: "arrow.up.arrow.down")
                        .font(theme.font(size: 14, weight: .semibold))
                        .foregroundStyle(theme.accent)
                        .frame(width: 32, height: 32)
                        .background(
                            Circle()
                                .fill(theme.surface)
                        )
                }
                .buttonStyle(.plain)
                Spacer()
            }

            // To field (result)
            VStack(alignment: .leading, spacing: 6) {
                Text("To")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(theme.secondary)

                HStack(spacing: 8) {
                    Text(formattedResult)
                        .font(theme.title(size: 24, weight: .semibold))
                        .foregroundStyle(theme.accent)
                        .frame(maxWidth: .infinity, alignment: .leading)

                    Picker("", selection: $data.toUnit) {
                        ForEach(currentUnits, id: \.self) { unit in
                            Text(unit).tag(unit)
                        }
                    }
                    .labelsHidden()
                    .frame(width: 70)
                }
                .padding(10)
                .background(
                    RoundedRectangle(cornerRadius: 10)
                        .fill(theme.surface)
                )
            }

            // Add to favorites
            Button {
                withAnimation {
                    var fav = FavoriteConversion()
                    fav.fromUnit = data.fromUnit
                    fav.toUnit = data.toUnit
                    fav.category = data.category
                    // Avoid duplicates
                    if !data.favorites.contains(where: {
                        $0.fromUnit == fav.fromUnit && $0.toUnit == fav.toUnit && $0.category == fav.category
                    }) {
                        data.favorites.append(fav)
                    }
                }
            } label: {
                Label("Save Conversion", systemImage: "star")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(theme.accent)
            }
            .buttonStyle(.plain)
        }
    }

    // MARK: - Export Conversion Result

    private var exportConversionResult: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(alignment: .firstTextBaseline, spacing: 4) {
                Text(formatNumber(data.inputValue))
                    .font(theme.title(size: 24, weight: .semibold))
                    .foregroundStyle(theme.foreground)
                Text(data.fromUnit)
                    .font(theme.font(size: 14, weight: .medium))
                    .foregroundStyle(theme.secondary)
            }

            Image(systemName: "equal")
                .font(theme.font(size: 14))
                .foregroundStyle(theme.secondary)

            HStack(alignment: .firstTextBaseline, spacing: 4) {
                Text(formattedResult)
                    .font(theme.title(size: 24, weight: .semibold))
                    .foregroundStyle(theme.accent)
                Text(data.toUnit)
                    .font(theme.font(size: 14, weight: .medium))
                    .foregroundStyle(theme.secondary)
            }
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(theme.surface)
        )
    }

    // MARK: - Shared Components

    private func favoriteLabel(_ fav: FavoriteConversion) -> some View {
        HStack(spacing: 4) {
            Image(systemName: "star.fill")
                .font(theme.font(size: 9))
                .foregroundStyle(theme.accent.opacity(0.7))
            Text("\(fav.fromUnit) \u{2192} \(fav.toUnit)")
                .font(.caption)
                .foregroundStyle(theme.foreground)
            Text("(\(fav.category))")
                .font(theme.font(size: 10))
                .foregroundStyle(theme.secondary.opacity(0.6))
        }
    }

    // MARK: - Conversion Logic

    private var allCategories: [String] {
        ["Length", "Weight", "Temperature", "Volume"]
    }

    private var currentUnits: [String] {
        units(for: data.category)
    }

    private func units(for category: String) -> [String] {
        switch category {
        case "Length":      return ["mm", "cm", "m", "km", "in", "ft", "yd", "mi"]
        case "Weight":      return ["mg", "g", "kg", "oz", "lb"]
        case "Temperature": return ["C", "F", "K"]
        case "Volume":      return ["ml", "L", "fl oz", "cup", "gal"]
        default:            return []
        }
    }

    private var convertedValue: Double? {
        convert(value: data.inputValue, from: data.fromUnit, to: data.toUnit, category: data.category)
    }

    private var formattedResult: String {
        guard let result = convertedValue else { return "--" }
        return formatNumber(result)
    }

    private func formatNumber(_ value: Double) -> String {
        if value == 0 { return "0" }
        let abs = Swift.abs(value)
        if abs >= 1000 {
            return String(format: "%.1f", value)
        } else if abs >= 1 {
            return String(format: "%.4g", value)
        } else if abs >= 0.001 {
            return String(format: "%.4g", value)
        } else {
            return String(format: "%.2e", value)
        }
    }

    // MARK: - Conversion Engine

    private func convert(value: Double, from: String, to: String, category: String) -> Double? {
        if from == to { return value }

        switch category {
        case "Length":
            guard let fromM = lengthToMeters(from), let toM = lengthToMeters(to) else { return nil }
            return value * fromM / toM
        case "Weight":
            guard let fromG = weightToGrams(from), let toG = weightToGrams(to) else { return nil }
            return value * fromG / toG
        case "Temperature":
            return convertTemperature(value: value, from: from, to: to)
        case "Volume":
            guard let fromML = volumeToML(from), let toML = volumeToML(to) else { return nil }
            return value * fromML / toML
        default:
            return nil
        }
    }

    // Length: factor to convert 1 unit -> meters
    private func lengthToMeters(_ unit: String) -> Double? {
        switch unit {
        case "mm": return 0.001
        case "cm": return 0.01
        case "m":  return 1.0
        case "km": return 1000.0
        case "in": return 0.0254
        case "ft": return 0.3048
        case "yd": return 0.9144
        case "mi": return 1609.344
        default:   return nil
        }
    }

    // Weight: factor to convert 1 unit -> grams
    private func weightToGrams(_ unit: String) -> Double? {
        switch unit {
        case "mg": return 0.001
        case "g":  return 1.0
        case "kg": return 1000.0
        case "oz": return 28.3495
        case "lb": return 453.592
        default:   return nil
        }
    }

    // Temperature: direct conversion
    private func convertTemperature(value: Double, from: String, to: String) -> Double? {
        // Convert to Celsius first
        let celsius: Double
        switch from {
        case "C": celsius = value
        case "F": celsius = (value - 32) * 5.0 / 9.0
        case "K": celsius = value - 273.15
        default: return nil
        }

        // Convert from Celsius to target
        switch to {
        case "C": return celsius
        case "F": return celsius * 9.0 / 5.0 + 32
        case "K": return celsius + 273.15
        default: return nil
        }
    }

    // Volume: factor to convert 1 unit -> milliliters
    private func volumeToML(_ unit: String) -> Double? {
        switch unit {
        case "ml":    return 1.0
        case "L":     return 1000.0
        case "fl oz": return 29.5735
        case "cup":   return 236.588
        case "gal":   return 3785.41
        default:      return nil
        }
    }
}

