import Foundation
import SwiftUI
import SlopKit

// MARK: - Data Model

@SlopData
public struct WaterDay: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("Date") var date: String = ""
    @Field("Count") var count: Double = 0
}

@SlopData
public struct WaterIntakeData {
    @SlopKit.Section("Overview")
    @Field("Title") var title: String = "Water Intake"
    @Field("Target Glasses") var targetGlasses: Double = 8
    @Field("Current Glasses") var currentGlasses: Double = 3
    @Field("Glass Size (ml)") var glassSize: Double = 250

    @SlopKit.Section("History")
    @Field("History") var history: [WaterDay] = WaterIntakeData.defaultHistory
}

extension WaterIntakeData {
    static var defaultHistory: [WaterDay] {
        func day(_ date: String, _ count: Double) -> WaterDay {
            var d = WaterDay()
            d.date = date
            d.count = count
            return d
        }

        return [
            day("Mon", 6),
            day("Tue", 8),
            day("Wed", 5),
            day("Thu", 7),
            day("Fri", 4),
            day("Sat", 8),
            day("Sun", 3),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.water-intake",
    name: "Water Intake",
    description: "Track glasses of water throughout the day with simple progress feedback.",
    version: "1.0.0",
    width: 280, height: 380,
    shape: .roundedRect(radius: 24),
    alwaysOnTop: true,
    categories: ["health"]
)
struct WaterIntakeView: View {
    @TemplateData var data: WaterIntakeData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    private var progress: Double {
        data.targetGlasses > 0 ? min(data.currentGlasses / data.targetGlasses, 1.0) : 0
    }

    var body: some View {
        SlopContent {
            VStack(spacing: 16) {
                SlopTextField("Title", text: $data.title)
                    .font(theme.font(size: 18, weight: .bold))
                    .foregroundStyle(theme.foreground)
                    .multilineTextAlignment(.center)

                // Water droplet icon
                dropletIcon

                // Big number display
                numberDisplay

                // Progress ring
                progressRing

                // Controls
                SlopInteractiveOnly {
                    HStack(spacing: 20) {
                        Button {
                            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                if data.currentGlasses > 0 {
                                    data.currentGlasses -= 1
                                }
                            }
                        } label: {
                            Image(systemName: "minus.circle.fill")
                                .font(theme.font(size: 28))
                                .foregroundStyle(theme.secondary)
                        }
                        .buttonStyle(.plain)

                        Button {
                            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                data.currentGlasses += 1
                            }
                        } label: {
                            Image(systemName: "plus.circle.fill")
                                .font(theme.font(size: 28))
                                .foregroundStyle(theme.accent)
                        }
                        .buttonStyle(.plain)

                        Button {
                            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                                data.currentGlasses = 0
                            }
                        } label: {
                            Image(systemName: "arrow.counterclockwise.circle.fill")
                                .font(theme.font(size: 22))
                                .foregroundStyle(theme.secondary.opacity(0.5))
                        }
                        .buttonStyle(.plain)
                    }
                }

                Divider().background(theme.divider)

                // Weekly history bar chart
                weeklyChart
            }
            .padding(20)
        }
        .background(theme.background)
        .animation(.spring(response: 0.3, dampingFraction: 0.7), value: data.currentGlasses)
    }

    // MARK: - Components

    private var dropletIcon: some View {
        ZStack {
            Image(systemName: "drop.fill")
                .font(theme.font(size: 40))
                .foregroundStyle(theme.accent.opacity(0.2))

            Image(systemName: "drop.fill")
                .font(theme.font(size: 40))
                .foregroundStyle(theme.accent)
                .mask(
                    VStack(spacing: 0) {
                        Color.clear
                            .frame(height: 40 * (1 - progress))
                        Rectangle()
                            .frame(height: 40 * progress)
                    }
                    .frame(width: 40, height: 40)
                )
        }
    }

    private var numberDisplay: some View {
        HStack(alignment: .firstTextBaseline, spacing: 4) {
            Text("\(Int(data.currentGlasses))")
                .font(theme.title(size: 36))
                .foregroundStyle(theme.accent)
            Text("/")
                .font(theme.font(size: 20, weight: .medium))
                .foregroundStyle(theme.secondary)
            Text("\(Int(data.targetGlasses))")
                .font(theme.font(size: 20, weight: .medium))
                .foregroundStyle(theme.secondary)
            Text("glasses")
                .font(.caption)
                .foregroundStyle(theme.secondary.opacity(0.6))
        }
    }

    private var progressRing: some View {
        ZStack {
            Circle()
                .stroke(theme.surface, lineWidth: 6)
                .frame(width: 60, height: 60)

            Circle()
                .trim(from: 0, to: progress)
                .stroke(theme.accent, style: StrokeStyle(lineWidth: 6, lineCap: .round))
                .rotationEffect(.degrees(-90))
                .frame(width: 60, height: 60)

            Text("\(Int(progress * 100))%")
                .font(theme.font(size: 12, weight: .bold))
                .foregroundStyle(theme.foreground)
        }
    }

    private var weeklyChart: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("This Week")
                .font(.caption.weight(.medium))
                .foregroundStyle(theme.secondary)

            HStack(alignment: .bottom, spacing: 6) {
                ForEach(data.history) { day in
                    VStack(spacing: 4) {
                        let maxCount = max(data.targetGlasses, 1)
                        let barHeight = max(4, 50 * min(day.count / maxCount, 1.0))

                        RoundedRectangle(cornerRadius: 3)
                            .fill(day.count >= data.targetGlasses ? theme.accent : theme.accent.opacity(0.4))
                            .frame(width: 20, height: barHeight)

                        Text(day.date)
                            .font(theme.font(size: 8, weight: .medium))
                            .foregroundStyle(theme.secondary.opacity(0.6))
                    }
                }
            }
            .frame(maxWidth: .infinity)
            .frame(height: 70, alignment: .bottom)
        }
    }
}

