import Foundation
import SwiftUI
import SlopKit

// MARK: - Data Model

@SlopData
public struct ClockEntry: Identifiable {
    @Field("ID") public var id: String = UUID().uuidString
    @Field("City Name") var cityName: String = ""
    @Field("Timezone ID") var timezoneID: String = "America/New_York"
    @Field("Color") var color: String = "#4a90d9"
}

@SlopData
public struct WorldClockData {
    @SlopKit.Section("Overview")
    @Field("Title") var title: String = "World Clock"

    @SlopKit.Section("Clocks")
    @Field("Clocks") var clocks: [ClockEntry] = WorldClockData.defaultClocks
}

extension WorldClockData {
    static var defaultClocks: [ClockEntry] {
        func clock(_ city: String, tz: String, color: String) -> ClockEntry {
            var c = ClockEntry()
            c.cityName = city
            c.timezoneID = tz
            c.color = color
            return c
        }

        return [
            clock("New York", tz: "America/New_York", color: "#4a90d9"),
            clock("London", tz: "Europe/London", color: "#e8608a"),
            clock("Tokyo", tz: "Asia/Tokyo", color: "#f5a623"),
        ]
    }
}

// MARK: - Template (generated by @SlopTemplate macro)

@SlopTemplate(
    id: "com.hitslop.templates.world-clock",
    name: "World Clock",
    description: "See multiple cities and time zones at once for distributed schedules.",
    version: "1.0.0",
    width: 320, height: 400,
    shape: .roundedRect(radius: 20),
    alwaysOnTop: true,
    categories: ["productivity"]
)
struct WorldClockView: View {
    @TemplateData var data: WorldClockData
    @Environment(\.slopTheme) private var theme
    @Environment(\.slopRenderTarget) private var renderTarget

    var body: some View {
        Group {
            if renderTarget == .interactive {
                ScrollView(showsIndicators: false) {
                    interactiveContent
                }
            } else {
                exportContent
            }
        }
        .background(theme.background)
    }

    // MARK: Interactive

    private var interactiveContent: some View {
        TimelineView(.periodic(from: .now, by: 1.0)) { context in
            VStack(alignment: .leading, spacing: 16) {
                SlopTextField("Title", text: $data.title)
                    .font(theme.title(size: 22))
                    .foregroundStyle(theme.foreground)

                Divider().background(theme.divider)

                ForEach($data.clocks) { $clock in
                    clockCard(clock: clock, clockBinding: $clock, date: context.date)
                }

                SlopInteractiveOnly {
                    Button {
                        withAnimation {
                            var c = ClockEntry()
                            c.cityName = "New City"
                            c.timezoneID = "UTC"
                            c.color = "#8e8e93"
                            data.clocks.append(c)
                        }
                    } label: {
                        Label("Add Clock", systemImage: "plus")
                            .font(.caption)
                            .foregroundStyle(theme.secondary.opacity(0.6))
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(24)
        }
    }

    private func clockCard(clock: ClockEntry, clockBinding: Binding<ClockEntry>, date: Date) -> some View {
        HStack(spacing: 0) {
            // Color accent bar
            RoundedRectangle(cornerRadius: 3)
                .fill(colorFromHex(clock.color))
                .frame(width: 6)

            VStack(alignment: .leading, spacing: 6) {
                HStack {
                    SlopTextField("City name", text: clockBinding.cityName)
                        .font(.headline)
                        .foregroundStyle(theme.foreground)
                    Spacer()
                    SlopInteractiveOnly {
                        Button {
                            withAnimation {
                                data.clocks.removeAll { $0.id == clock.id }
                            }
                        } label: {
                            Image(systemName: "minus.circle.fill")
                                .font(.caption)
                                .foregroundStyle(theme.secondary.opacity(0.4))
                        }
                        .buttonStyle(.plain)
                    }
                }

                Text(formattedTime(for: clock.timezoneID, at: date))
                    .font(theme.title(size: 36))
                    .foregroundStyle(colorFromHex(clock.color))

                HStack(spacing: 8) {
                    Text(timezoneAbbreviation(for: clock.timezoneID, at: date))
                        .font(.caption)
                        .foregroundStyle(theme.secondary)

                    Text(offsetFromLocal(for: clock.timezoneID, at: date))
                        .font(.caption)
                        .foregroundStyle(theme.secondary.opacity(0.7))
                }

                SlopInteractiveOnly {
                    HStack(spacing: 8) {
                        SlopTimeZonePicker(identifier: clockBinding.timezoneID)
                        SlopColorField(hex: clockBinding.color)
                    }
                }
            }
            .padding(12)
        }
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(theme.surface)
        )
    }

    // MARK: Export

    private var exportContent: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text(data.title)
                .font(theme.title(size: 22))
                .foregroundStyle(theme.foreground)

            Divider().background(theme.divider)

            let now = Date()
            ForEach(data.clocks) { clock in
                HStack(spacing: 0) {
                    // Color accent bar
                    RoundedRectangle(cornerRadius: 3)
                        .fill(colorFromHex(clock.color))
                        .frame(width: 6)

                    VStack(alignment: .leading, spacing: 6) {
                        Text(clock.cityName)
                            .font(.headline)
                            .foregroundStyle(theme.foreground)

                        Text(formattedTime(for: clock.timezoneID, at: now))
                            .font(theme.title(size: 36))
                            .foregroundStyle(colorFromHex(clock.color))

                        HStack(spacing: 8) {
                            Text(timezoneAbbreviation(for: clock.timezoneID, at: now))
                                .font(.caption)
                                .foregroundStyle(theme.secondary)

                            Text(offsetFromLocal(for: clock.timezoneID, at: now))
                                .font(.caption)
                                .foregroundStyle(theme.secondary.opacity(0.7))
                        }
                    }
                    .padding(12)
                }
                .background(
                    RoundedRectangle(cornerRadius: 10)
                        .fill(theme.surface)
                )
            }
        }
        .padding(24)
    }

    // MARK: Helpers

    private func timeZone(for identifier: String) -> TimeZone {
        TimeZone(identifier: identifier) ?? TimeZone(identifier: "UTC")!
    }

    private func formattedTime(for timezoneID: String, at date: Date) -> String {
        let formatter = DateFormatter()
        formatter.timeZone = timeZone(for: timezoneID)
        formatter.dateFormat = "HH:mm:ss"
        return formatter.string(from: date)
    }

    private func timezoneAbbreviation(for timezoneID: String, at date: Date) -> String {
        let tz = timeZone(for: timezoneID)
        return tz.abbreviation(for: date) ?? tz.identifier
    }

    private func offsetFromLocal(for timezoneID: String, at date: Date) -> String {
        let tz = timeZone(for: timezoneID)
        let localOffset = TimeZone.current.secondsFromGMT(for: date)
        let remoteOffset = tz.secondsFromGMT(for: date)
        let diffHours = Double(remoteOffset - localOffset) / 3600.0

        if diffHours == 0 {
            return "(local)"
        }

        let sign = diffHours > 0 ? "+" : ""
        if diffHours == diffHours.rounded() {
            return "(\(sign)\(Int(diffHours))h)"
        } else {
            return String(format: "(%@%.1fh)", sign, diffHours)
        }
    }
}
