import SwiftUI

/// Protocol that template data models conform to (generated by @Template macro).
public protocol TemplateDataProtocol: Sendable {
    /// Static schema describing the data model's fields for the host inspector.
    static var schema: Schema { get }

    /// Hydrate from generic field values (host -> template).
    init(from values: [String: FieldValue])

    /// Serialize back to generic field values (template -> host).
    func toFieldValues() -> [String: FieldValue]
}

/// Type-erased protocol for dynamic bundle loading.
/// The host works with this — no knowledge of the concrete Data type.
public protocol AnySlopTemplate: AnyObject {
    static var templateID: String { get }
    static var name: String { get }
    static var templateDescription: String? { get }
    static var version: String { get }
    static var minimumHostVersion: String { get }
    static var schema: Schema { get }
    static var metadata: TemplateMetadata { get }

    @MainActor
    init(rawStore: RawTemplateStore)
    @MainActor
    init(rawStore: RawTemplateStore, sidecarStore: SidecarStore)
    @MainActor
    func body() -> AnyView
}

public extension AnySlopTemplate {
    static var templateDescription: String? { nil }
    static var minimumHostVersion: String { "1.0.0" }

    /// Default: delegates to `init(rawStore:)`, ignoring the sidecar store.
    /// Templates that use sidecar files override this.
    @MainActor
    init(rawStore: RawTemplateStore, sidecarStore: SidecarStore) {
        self.init(rawStore: rawStore)
    }
}
